// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Controller manages active jobs, steering commands, and coworker soul interactions.
 */
export interface Controller {
}
