# NovelClaw build & release helpers.
#
# Versioning has ONE source of truth: the `Version` constant in
# pkg/appmeta/version.go. Bump it there, tag the release `v<same-version>`
# (app "1.2.3" ↔ tag "v1.2.3"), and the self-updater will pick the release up.
# There is no -ldflags injection and no version environment variable.

APP_NAME  := novelclaw
VERSION   := $(shell sed -n 's/^const Version = "\(.*\)"$$/\1/p' pkg/appmeta/version.go)
CONFIG    := build/config.yml

icon:
	@echo Updating icons...
	magick build/appicon.png -define icon:auto-resize=16,24,32,48,64,128,256 build/windows/icon.ico
	magick build/appicon.png -define icon:auto-resize=16,24,32,48,64,128,256,512 build/windows/icons.ico
	@echo Done!

# Mirror pkg/appmeta/version.go into the bundle metadata that Wails bakes into
# Info.plist / MSIX (build/config.yml `info.version`) and regenerate the build
# assets from it, so the OS-level version can never drift from the version the
# updater compares against.
sync-version:
	@test -n "$(VERSION)" || { echo "cannot read Version from pkg/appmeta/version.go"; exit 1; }
	@sed 's/^  version: ".*"/  version: "$(VERSION)"/' $(CONFIG) > $(CONFIG).tmp && mv $(CONFIG).tmp $(CONFIG)
	@wails3 update build-assets -name "$(APP_NAME)" -binaryname "$(APP_NAME)" -config $(CONFIG) >/dev/null
	@echo "Bundle version synced to $(VERSION)"

dev:
	@echo Starting development server...
	wails3 dev
	@echo Done!

build:
	@echo Building version $(VERSION)...
	go build -o bin/$(APP_NAME) .
	@echo Done!

generate:
	@echo Generating bindings...
	wails3 generate bindings -ts
	@echo Done!

release-win-amd64: sync-version
	@echo Building release application (windows/amd64) version $(VERSION)...
	wails3 package GOOS=windows GOARCH=amd64
	@echo Done!

release-win-arm64: sync-version
	@echo Building release application (windows/arm64) version $(VERSION)...
	wails3 package GOOS=windows GOARCH=arm64
	@echo Done!

release-linux-amd64: sync-version
	@echo Building release application (linux/amd64) version $(VERSION)...
	wails3 package GOOS=linux GOARCH=amd64
	@echo Done!

release-darwin-amd64: sync-version
	@echo Building release application (darwin/amd64) version $(VERSION)...
	wails3 package GOOS=darwin GOARCH=amd64
	@echo Done!

release-darwin-arm64: sync-version
	@echo Building release application (darwin/arm64) version $(VERSION)...
	wails3 package GOOS=darwin GOARCH=arm64
	@echo Done!

# Checksums are generated by CI over the merged asset set. This target is for
# verifying a local package output before pushing a tag.
checksums:
	@echo Generating SHA256SUMS for release assets...
	cd bin && shasum -a 256 novelclaw-* > SHA256SUMS && cat SHA256SUMS
	@echo Done!

update:
	@echo Updating build assets...
	wails3 update build-assets -name "$(APP_NAME)" -binaryname "$(APP_NAME)" -config $(CONFIG)
	@echo Done!

.PHONY: icon sync-version dev build generate checksums update release-win-amd64 release-win-arm64 release-linux-amd64 release-darwin-amd64 release-darwin-arm64
