// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Registry manages modular skills, project-specific settings, and dynamic prompt assembly.
 */
export class Registry {

    /** Creates a new Registry instance. */
    constructor($$source: Partial<Registry> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Registry instance from a string or object.
     */
    static createFrom($$source: any = {}): Registry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Registry($$parsedSource as Partial<Registry>);
    }
}

/**
 * StorageManager manages hierarchical skill persistence:
 * - Default (Factory) immutable baseline: `skills/default/`
 * - Evolved per-project mutations: `skills/evolved/<project_id>/`
 */
export class StorageManager {

    /** Creates a new StorageManager instance. */
    constructor($$source: Partial<StorageManager> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StorageManager instance from a string or object.
     */
    static createFrom($$source: any = {}): StorageManager {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StorageManager($$parsedSource as Partial<StorageManager>);
    }
}
