// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Registry manages modular skills, project-specific settings, and dynamic prompt assembly.
 */
export interface Registry {
}

/**
 * StorageManager manages hierarchical skill persistence:
 * - Default (Factory) immutable baseline: `skills/default/`
 * - Evolved per-project mutations: `skills/evolved/<project_id>/`
 */
export interface StorageManager {
}
