// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AppInfo {
    "version": string;
    "repo": string;
    "platform": string;
    "data_dir": string;
}
