// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppendBookRequest specifies a book file to append as a new volume to an existing project/series.
 */
export class AppendBookRequest {
    "project_id": string;
    "file_path": string;
    "vol_name"?: string;

    /** Creates a new AppendBookRequest instance. */
    constructor($$source: Partial<AppendBookRequest> = {}) {
        if (!("project_id" in $$source)) {
            this["project_id"] = "";
        }
        if (!("file_path" in $$source)) {
            this["file_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppendBookRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): AppendBookRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppendBookRequest($$parsedSource as Partial<AppendBookRequest>);
    }
}

/**
 * AutoScanRequest specifies parameters for AI auto-extracting characters and relations.
 */
export class AutoScanRequest {
    "project_id": string;
    "chapter_index"?: number;

    /**
     * "volume" (default), "pre_scan", "current_chapter", "all"
     */
    "scan_mode": string;
    "volume"?: string;

    /** Creates a new AutoScanRequest instance. */
    constructor($$source: Partial<AutoScanRequest> = {}) {
        if (!("project_id" in $$source)) {
            this["project_id"] = "";
        }
        if (!("scan_mode" in $$source)) {
            this["scan_mode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AutoScanRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): AutoScanRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AutoScanRequest($$parsedSource as Partial<AutoScanRequest>);
    }
}

/**
 * AutoScanResultDTO contains the results of AI auto-scanning entities and relations.
 */
export class AutoScanResultDTO {
    "success": boolean;
    "message": string;
    "entities_found": number;
    "relations_found": number;
    "duration_ms": number;
    "volume_scanned"?: string;
    "effective_chapter": number;
    "discovered_entities": EntityDTO[];
    "discovered_relations": RelationDTO[];

    /** Creates a new AutoScanResultDTO instance. */
    constructor($$source: Partial<AutoScanResultDTO> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("entities_found" in $$source)) {
            this["entities_found"] = 0;
        }
        if (!("relations_found" in $$source)) {
            this["relations_found"] = 0;
        }
        if (!("duration_ms" in $$source)) {
            this["duration_ms"] = 0;
        }
        if (!("effective_chapter" in $$source)) {
            this["effective_chapter"] = 0;
        }
        if (!("discovered_entities" in $$source)) {
            this["discovered_entities"] = [];
        }
        if (!("discovered_relations" in $$source)) {
            this["discovered_relations"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AutoScanResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): AutoScanResultDTO {
        const $$createField7_0 = $$createType1;
        const $$createField8_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("discovered_entities" in $$parsedSource) {
            $$parsedSource["discovered_entities"] = $$createField7_0($$parsedSource["discovered_entities"]);
        }
        if ("discovered_relations" in $$parsedSource) {
            $$parsedSource["discovered_relations"] = $$createField8_0($$parsedSource["discovered_relations"]);
        }
        return new AutoScanResultDTO($$parsedSource as Partial<AutoScanResultDTO>);
    }
}

/**
 * AutoScoutStyleRequest requests autonomous literary style analysis across opening novel chapters.
 */
export class AutoScoutStyleRequest {
    "project_id": string;
    "source_lang": string;
    "target_lang": string;

    /** Creates a new AutoScoutStyleRequest instance. */
    constructor($$source: Partial<AutoScoutStyleRequest> = {}) {
        if (!("project_id" in $$source)) {
            this["project_id"] = "";
        }
        if (!("source_lang" in $$source)) {
            this["source_lang"] = "";
        }
        if (!("target_lang" in $$source)) {
            this["target_lang"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AutoScoutStyleRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): AutoScoutStyleRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AutoScoutStyleRequest($$parsedSource as Partial<AutoScoutStyleRequest>);
    }
}

/**
 * AutoScoutStyleResponse returns the LLM's tailored literary style profile.
 */
export class AutoScoutStyleResponse {
    "success": boolean;
    "style_name": string;
    "style_description": string;
    "style_prompt": string;
    "analysis_notes": string;
    "sample_excerpt": string;
    "sample_translated": string;
    "model_used": string;
    "latency_ms": number;
    "chapters_sampled": number;
    "error"?: string;

    /** Creates a new AutoScoutStyleResponse instance. */
    constructor($$source: Partial<AutoScoutStyleResponse> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("style_name" in $$source)) {
            this["style_name"] = "";
        }
        if (!("style_description" in $$source)) {
            this["style_description"] = "";
        }
        if (!("style_prompt" in $$source)) {
            this["style_prompt"] = "";
        }
        if (!("analysis_notes" in $$source)) {
            this["analysis_notes"] = "";
        }
        if (!("sample_excerpt" in $$source)) {
            this["sample_excerpt"] = "";
        }
        if (!("sample_translated" in $$source)) {
            this["sample_translated"] = "";
        }
        if (!("model_used" in $$source)) {
            this["model_used"] = "";
        }
        if (!("latency_ms" in $$source)) {
            this["latency_ms"] = 0;
        }
        if (!("chapters_sampled" in $$source)) {
            this["chapters_sampled"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AutoScoutStyleResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): AutoScoutStyleResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AutoScoutStyleResponse($$parsedSource as Partial<AutoScoutStyleResponse>);
    }
}

/**
 * BatchImportBookRequest specifies multiple files to ingest into the studio.
 */
export class BatchImportBookRequest {
    "file_paths": string[];
    "source_lang"?: string;
    "target_lang"?: string;
    "as_series": boolean;
    "series_name"?: string;

    /** Creates a new BatchImportBookRequest instance. */
    constructor($$source: Partial<BatchImportBookRequest> = {}) {
        if (!("file_paths" in $$source)) {
            this["file_paths"] = [];
        }
        if (!("as_series" in $$source)) {
            this["as_series"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatchImportBookRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): BatchImportBookRequest {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("file_paths" in $$parsedSource) {
            $$parsedSource["file_paths"] = $$createField0_0($$parsedSource["file_paths"]);
        }
        return new BatchImportBookRequest($$parsedSource as Partial<BatchImportBookRequest>);
    }
}

/**
 * BatchImportResultDTO summarizes the results of batch file ingestion.
 */
export class BatchImportResultDTO {
    "total_files": number;
    "success_count": number;
    "failed_count": number;
    "projects": ProjectDTO[];
    "error_messages"?: string[];

    /** Creates a new BatchImportResultDTO instance. */
    constructor($$source: Partial<BatchImportResultDTO> = {}) {
        if (!("total_files" in $$source)) {
            this["total_files"] = 0;
        }
        if (!("success_count" in $$source)) {
            this["success_count"] = 0;
        }
        if (!("failed_count" in $$source)) {
            this["failed_count"] = 0;
        }
        if (!("projects" in $$source)) {
            this["projects"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatchImportResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): BatchImportResultDTO {
        const $$createField3_0 = $$createType6;
        const $$createField4_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("projects" in $$parsedSource) {
            $$parsedSource["projects"] = $$createField3_0($$parsedSource["projects"]);
        }
        if ("error_messages" in $$parsedSource) {
            $$parsedSource["error_messages"] = $$createField4_0($$parsedSource["error_messages"]);
        }
        return new BatchImportResultDTO($$parsedSource as Partial<BatchImportResultDTO>);
    }
}

/**
 * BenchmarkMetricsDTO represents performance data for a specific translation mode.
 */
export class BenchmarkMetricsDTO {
    "mode": string;
    "chapters_count": number;
    "total_runes": number;
    "duration_ms": number;
    "runes_per_second": number;
    "tokens_per_second": number;
    "prompt_tokens": number;
    "completion_tokens": number;
    "total_tokens": number;
    "reasoning_tokens": number;
    "estimated_cost_usd": number;
    "pronoun_consistency_score": number;
    "revised_count": number;

    /** Creates a new BenchmarkMetricsDTO instance. */
    constructor($$source: Partial<BenchmarkMetricsDTO> = {}) {
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("chapters_count" in $$source)) {
            this["chapters_count"] = 0;
        }
        if (!("total_runes" in $$source)) {
            this["total_runes"] = 0;
        }
        if (!("duration_ms" in $$source)) {
            this["duration_ms"] = 0;
        }
        if (!("runes_per_second" in $$source)) {
            this["runes_per_second"] = 0;
        }
        if (!("tokens_per_second" in $$source)) {
            this["tokens_per_second"] = 0;
        }
        if (!("prompt_tokens" in $$source)) {
            this["prompt_tokens"] = 0;
        }
        if (!("completion_tokens" in $$source)) {
            this["completion_tokens"] = 0;
        }
        if (!("total_tokens" in $$source)) {
            this["total_tokens"] = 0;
        }
        if (!("reasoning_tokens" in $$source)) {
            this["reasoning_tokens"] = 0;
        }
        if (!("estimated_cost_usd" in $$source)) {
            this["estimated_cost_usd"] = 0;
        }
        if (!("pronoun_consistency_score" in $$source)) {
            this["pronoun_consistency_score"] = 0;
        }
        if (!("revised_count" in $$source)) {
            this["revised_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BenchmarkMetricsDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): BenchmarkMetricsDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BenchmarkMetricsDTO($$parsedSource as Partial<BenchmarkMetricsDTO>);
    }
}

/**
 * BenchmarkReportDTO summarizes comparative benchmarks across modes.
 */
export class BenchmarkReportDTO {
    "project_id": string;
    "timestamp": string;
    "results": BenchmarkMetricsDTO[];
    "markdown_report": string;

    /** Creates a new BenchmarkReportDTO instance. */
    constructor($$source: Partial<BenchmarkReportDTO> = {}) {
        if (!("project_id" in $$source)) {
            this["project_id"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "";
        }
        if (!("results" in $$source)) {
            this["results"] = [];
        }
        if (!("markdown_report" in $$source)) {
            this["markdown_report"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BenchmarkReportDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): BenchmarkReportDTO {
        const $$createField2_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField2_0($$parsedSource["results"]);
        }
        return new BenchmarkReportDTO($$parsedSource as Partial<BenchmarkReportDTO>);
    }
}

/**
 * ChapterDTO represents an individual chapter for the workspace UI.
 */
export class ChapterDTO {
    "id": string;
    "project_id": string;
    "chapter_index": number;
    "title": string;
    "content_path": string;
    "raw_content": string;
    "translated_content": string;
    "status": string;
    "created_at": string;
    "updated_at": string;

    /** Creates a new ChapterDTO instance. */
    constructor($$source: Partial<ChapterDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("project_id" in $$source)) {
            this["project_id"] = "";
        }
        if (!("chapter_index" in $$source)) {
            this["chapter_index"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("content_path" in $$source)) {
            this["content_path"] = "";
        }
        if (!("raw_content" in $$source)) {
            this["raw_content"] = "";
        }
        if (!("translated_content" in $$source)) {
            this["translated_content"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChapterDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ChapterDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChapterDTO($$parsedSource as Partial<ChapterDTO>);
    }
}

/**
 * CharacterVoiceDTO conveys persona and dialogue style rules for character voice prompting.
 */
export class CharacterVoiceDTO {
    "character_id": string;
    "name": string;
    "aliases": string[];
    "voice_tone": string;
    "dialogue_rules": string[];
    "catchphrases": string[];

    /** Creates a new CharacterVoiceDTO instance. */
    constructor($$source: Partial<CharacterVoiceDTO> = {}) {
        if (!("character_id" in $$source)) {
            this["character_id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("aliases" in $$source)) {
            this["aliases"] = [];
        }
        if (!("voice_tone" in $$source)) {
            this["voice_tone"] = "";
        }
        if (!("dialogue_rules" in $$source)) {
            this["dialogue_rules"] = [];
        }
        if (!("catchphrases" in $$source)) {
            this["catchphrases"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CharacterVoiceDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): CharacterVoiceDTO {
        const $$createField2_0 = $$createType4;
        const $$createField4_0 = $$createType4;
        const $$createField5_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("aliases" in $$parsedSource) {
            $$parsedSource["aliases"] = $$createField2_0($$parsedSource["aliases"]);
        }
        if ("dialogue_rules" in $$parsedSource) {
            $$parsedSource["dialogue_rules"] = $$createField4_0($$parsedSource["dialogue_rules"]);
        }
        if ("catchphrases" in $$parsedSource) {
            $$parsedSource["catchphrases"] = $$createField5_0($$parsedSource["catchphrases"]);
        }
        return new CharacterVoiceDTO($$parsedSource as Partial<CharacterVoiceDTO>);
    }
}

/**
 * CompactThreadResponse contains results after compacting a thread.
 */
export class CompactThreadResponse {
    "thread_id": string;
    "original_tokens": number;
    "compacted_tokens": number;
    "archived_messages": number;
    "summary_notice": string;

    /** Creates a new CompactThreadResponse instance. */
    constructor($$source: Partial<CompactThreadResponse> = {}) {
        if (!("thread_id" in $$source)) {
            this["thread_id"] = "";
        }
        if (!("original_tokens" in $$source)) {
            this["original_tokens"] = 0;
        }
        if (!("compacted_tokens" in $$source)) {
            this["compacted_tokens"] = 0;
        }
        if (!("archived_messages" in $$source)) {
            this["archived_messages"] = 0;
        }
        if (!("summary_notice" in $$source)) {
            this["summary_notice"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompactThreadResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): CompactThreadResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CompactThreadResponse($$parsedSource as Partial<CompactThreadResponse>);
    }
}

/**
 * CreateProjectRequest contains parameters for creating a new translation project.
 */
export class CreateProjectRequest {
    "id": string;
    "title": string;
    "author": string;
    "source_lang": string;
    "target_lang": string;
    "original_format": string;
    "total_chapters": number;

    /** Creates a new CreateProjectRequest instance. */
    constructor($$source: Partial<CreateProjectRequest> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("source_lang" in $$source)) {
            this["source_lang"] = "";
        }
        if (!("target_lang" in $$source)) {
            this["target_lang"] = "";
        }
        if (!("original_format" in $$source)) {
            this["original_format"] = "";
        }
        if (!("total_chapters" in $$source)) {
            this["total_chapters"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateProjectRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateProjectRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateProjectRequest($$parsedSource as Partial<CreateProjectRequest>);
    }
}

/**
 * CreateSubThreadRequest represents parameters to create a new sub-chat thread.
 */
export class CreateSubThreadRequest {
    "project_id": string;
    "title": string;
    "volume_index": number;
    "chapter_index": number;

    /** Creates a new CreateSubThreadRequest instance. */
    constructor($$source: Partial<CreateSubThreadRequest> = {}) {
        if (!("project_id" in $$source)) {
            this["project_id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("volume_index" in $$source)) {
            this["volume_index"] = 0;
        }
        if (!("chapter_index" in $$source)) {
            this["chapter_index"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateSubThreadRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateSubThreadRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateSubThreadRequest($$parsedSource as Partial<CreateSubThreadRequest>);
    }
}

/**
 * DownloadGlossaryRequest contains parameters for downloading and importing a remote dictionary file.
 */
export class DownloadGlossaryRequest {
    "project_id": string;
    "url": string;

    /**
     * "vietphrase" | "tsv" | "json"
     */
    "format": string;
    "default_category": string;

    /** Creates a new DownloadGlossaryRequest instance. */
    constructor($$source: Partial<DownloadGlossaryRequest> = {}) {
        if (!("project_id" in $$source)) {
            this["project_id"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("format" in $$source)) {
            this["format"] = "";
        }
        if (!("default_category" in $$source)) {
            this["default_category"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadGlossaryRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): DownloadGlossaryRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DownloadGlossaryRequest($$parsedSource as Partial<DownloadGlossaryRequest>);
    }
}

/**
 * EntityDTO represents a character or entity node in the story graph.
 */
export class EntityDTO {
    "id": string;
    "project_id": string;
    "name": string;
    "aliases": string[];
    "category": string;
    "gender": string;
    "role": string;
    "first_seen_chapter": number;
    "metadata": { [_ in string]?: any };

    /** Creates a new EntityDTO instance. */
    constructor($$source: Partial<EntityDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("project_id" in $$source)) {
            this["project_id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("aliases" in $$source)) {
            this["aliases"] = [];
        }
        if (!("category" in $$source)) {
            this["category"] = "";
        }
        if (!("gender" in $$source)) {
            this["gender"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("first_seen_chapter" in $$source)) {
            this["first_seen_chapter"] = 0;
        }
        if (!("metadata" in $$source)) {
            this["metadata"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EntityDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): EntityDTO {
        const $$createField3_0 = $$createType4;
        const $$createField8_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("aliases" in $$parsedSource) {
            $$parsedSource["aliases"] = $$createField3_0($$parsedSource["aliases"]);
        }
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField8_0($$parsedSource["metadata"]);
        }
        return new EntityDTO($$parsedSource as Partial<EntityDTO>);
    }
}

/**
 * ExecutionTelemetryDTO represents quantitative telemetry after translation completes.
 */
export class ExecutionTelemetryDTO {
    "mode": string;
    "duration_ms": number;
    "prompt_tokens": number;
    "completion_tokens": number;
    "total_tokens": number;
    "reasoning_tokens": number;
    "revised_count": number;
    "tool_calls_count": number;
    "total_runes": number;
    "runes_per_second": number;
    "tokens_per_second": number;
    "estimated_cost_usd": number;

    /** Creates a new ExecutionTelemetryDTO instance. */
    constructor($$source: Partial<ExecutionTelemetryDTO> = {}) {
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("duration_ms" in $$source)) {
            this["duration_ms"] = 0;
        }
        if (!("prompt_tokens" in $$source)) {
            this["prompt_tokens"] = 0;
        }
        if (!("completion_tokens" in $$source)) {
            this["completion_tokens"] = 0;
        }
        if (!("total_tokens" in $$source)) {
            this["total_tokens"] = 0;
        }
        if (!("reasoning_tokens" in $$source)) {
            this["reasoning_tokens"] = 0;
        }
        if (!("revised_count" in $$source)) {
            this["revised_count"] = 0;
        }
        if (!("tool_calls_count" in $$source)) {
            this["tool_calls_count"] = 0;
        }
        if (!("total_runes" in $$source)) {
            this["total_runes"] = 0;
        }
        if (!("runes_per_second" in $$source)) {
            this["runes_per_second"] = 0;
        }
        if (!("tokens_per_second" in $$source)) {
            this["tokens_per_second"] = 0;
        }
        if (!("estimated_cost_usd" in $$source)) {
            this["estimated_cost_usd"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExecutionTelemetryDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ExecutionTelemetryDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExecutionTelemetryDTO($$parsedSource as Partial<ExecutionTelemetryDTO>);
    }
}

/**
 * ExportBundleRequest specifies the project ID and destination path for a .neko bundle.
 */
export class ExportBundleRequest {
    "project_id": string;
    "output_path": string;

    /** Creates a new ExportBundleRequest instance. */
    constructor($$source: Partial<ExportBundleRequest> = {}) {
        if (!("project_id" in $$source)) {
            this["project_id"] = "";
        }
        if (!("output_path" in $$source)) {
            this["output_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportBundleRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportBundleRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportBundleRequest($$parsedSource as Partial<ExportBundleRequest>);
    }
}

/**
 * ExportEbookRequest defines the parameters for synthesizing an ebook.
 */
export class ExportEbookRequest {
    "project_id": string;
    "target_format": string;
    "output_path": string;
    "custom_title"?: string;
    "custom_author"?: string;
    "cover_image_path"?: string;
    "use_translated_only": boolean;
    "volume"?: string;

    /** Creates a new ExportEbookRequest instance. */
    constructor($$source: Partial<ExportEbookRequest> = {}) {
        if (!("project_id" in $$source)) {
            this["project_id"] = "";
        }
        if (!("target_format" in $$source)) {
            this["target_format"] = "";
        }
        if (!("output_path" in $$source)) {
            this["output_path"] = "";
        }
        if (!("use_translated_only" in $$source)) {
            this["use_translated_only"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportEbookRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportEbookRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportEbookRequest($$parsedSource as Partial<ExportEbookRequest>);
    }
}

/**
 * ExportResultDTO represents the outcome of an export or bundle packaging operation.
 */
export class ExportResultDTO {
    "output_path": string;
    "format": string;
    "file_size_bytes": number;
    "chapter_count": number;
    "duration_ms": number;

    /** Creates a new ExportResultDTO instance. */
    constructor($$source: Partial<ExportResultDTO> = {}) {
        if (!("output_path" in $$source)) {
            this["output_path"] = "";
        }
        if (!("format" in $$source)) {
            this["format"] = "";
        }
        if (!("file_size_bytes" in $$source)) {
            this["file_size_bytes"] = 0;
        }
        if (!("chapter_count" in $$source)) {
            this["chapter_count"] = 0;
        }
        if (!("duration_ms" in $$source)) {
            this["duration_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportResultDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportResultDTO($$parsedSource as Partial<ExportResultDTO>);
    }
}

/**
 * FewShotExampleDTO holds a demonstration pair for a skill.
 */
export class FewShotExampleDTO {
    "input": string;
    "output": string;
    "note"?: string;

    /** Creates a new FewShotExampleDTO instance. */
    constructor($$source: Partial<FewShotExampleDTO> = {}) {
        if (!("input" in $$source)) {
            this["input"] = "";
        }
        if (!("output" in $$source)) {
            this["output"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FewShotExampleDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): FewShotExampleDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FewShotExampleDTO($$parsedSource as Partial<FewShotExampleDTO>);
    }
}

/**
 * FormatDescriptorDTO provides user-friendly metadata for each supported export format.
 */
export class FormatDescriptorDTO {
    "format": string;
    "name": string;
    "extension": string;
    "description": string;
    "recommended_for": string;

    /** Creates a new FormatDescriptorDTO instance. */
    constructor($$source: Partial<FormatDescriptorDTO> = {}) {
        if (!("format" in $$source)) {
            this["format"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("extension" in $$source)) {
            this["extension"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("recommended_for" in $$source)) {
            this["recommended_for"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FormatDescriptorDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): FormatDescriptorDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FormatDescriptorDTO($$parsedSource as Partial<FormatDescriptorDTO>);
    }
}

/**
 * GlossaryTermDTO represents a terminology entry for frontend display.
 */
export class GlossaryTermDTO {
    "id": string;
    "project_id": string;
    "source_term": string;
    "target_term": string;
    "category": string;
    "notes": string;
    "created_at": string;

    /** Creates a new GlossaryTermDTO instance. */
    constructor($$source: Partial<GlossaryTermDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("project_id" in $$source)) {
            this["project_id"] = "";
        }
        if (!("source_term" in $$source)) {
            this["source_term"] = "";
        }
        if (!("target_term" in $$source)) {
            this["target_term"] = "";
        }
        if (!("category" in $$source)) {
            this["category"] = "";
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GlossaryTermDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): GlossaryTermDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GlossaryTermDTO($$parsedSource as Partial<GlossaryTermDTO>);
    }
}

/**
 * GraphReadinessDTO conveys whether the graph is ready and up-to-date for a specific chapter/volume.
 */
export class GraphReadinessDTO {
    "is_ready": boolean;
    "project_id": string;
    "chapter_index": number;
    "volume_tag"?: string;
    "volume_start_chapter"?: number;
    "volume_end_chapter"?: number;
    "has_volume_scan": boolean;
    "volume_relations_count": number;
    "total_project_relations": number;
    "total_project_entities": number;
    "message": string;

    /** Creates a new GraphReadinessDTO instance. */
    constructor($$source: Partial<GraphReadinessDTO> = {}) {
        if (!("is_ready" in $$source)) {
            this["is_ready"] = false;
        }
        if (!("project_id" in $$source)) {
            this["project_id"] = "";
        }
        if (!("chapter_index" in $$source)) {
            this["chapter_index"] = 0;
        }
        if (!("has_volume_scan" in $$source)) {
            this["has_volume_scan"] = false;
        }
        if (!("volume_relations_count" in $$source)) {
            this["volume_relations_count"] = 0;
        }
        if (!("total_project_relations" in $$source)) {
            this["total_project_relations"] = 0;
        }
        if (!("total_project_entities" in $$source)) {
            this["total_project_entities"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphReadinessDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): GraphReadinessDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GraphReadinessDTO($$parsedSource as Partial<GraphReadinessDTO>);
    }
}

/**
 * ImportBookRequest describes a book file to parse and ingest into a new project.
 */
export class ImportBookRequest {
    "file_path": string;
    "project_id"?: string;
    "source_lang"?: string;
    "target_lang"?: string;

    /** Creates a new ImportBookRequest instance. */
    constructor($$source: Partial<ImportBookRequest> = {}) {
        if (!("file_path" in $$source)) {
            this["file_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportBookRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportBookRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportBookRequest($$parsedSource as Partial<ImportBookRequest>);
    }
}

/**
 * InheritKnowledgeRequest specifies source and target project for copying universe knowledge.
 */
export class InheritKnowledgeRequest {
    "source_project_id": string;
    "target_project_id": string;

    /** Creates a new InheritKnowledgeRequest instance. */
    constructor($$source: Partial<InheritKnowledgeRequest> = {}) {
        if (!("source_project_id" in $$source)) {
            this["source_project_id"] = "";
        }
        if (!("target_project_id" in $$source)) {
            this["target_project_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InheritKnowledgeRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): InheritKnowledgeRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InheritKnowledgeRequest($$parsedSource as Partial<InheritKnowledgeRequest>);
    }
}

/**
 * InheritKnowledgeResultDTO returns the count of copied items.
 */
export class InheritKnowledgeResultDTO {
    "entities_count": number;
    "relations_count": number;
    "glossary_count": number;
    "success": boolean;

    /** Creates a new InheritKnowledgeResultDTO instance. */
    constructor($$source: Partial<InheritKnowledgeResultDTO> = {}) {
        if (!("entities_count" in $$source)) {
            this["entities_count"] = 0;
        }
        if (!("relations_count" in $$source)) {
            this["relations_count"] = 0;
        }
        if (!("glossary_count" in $$source)) {
            this["glossary_count"] = 0;
        }
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InheritKnowledgeResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): InheritKnowledgeResultDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InheritKnowledgeResultDTO($$parsedSource as Partial<InheritKnowledgeResultDTO>);
    }
}

/**
 * LLMConfigDTO represents an LLM provider configuration with masked sensitive tokens.
 */
export class LLMConfigDTO {
    "id": string;
    "provider_name": string;
    "api_url": string;
    "masked_token": string;
    "has_token": boolean;
    "model_name": string;
    "is_active": boolean;
    "is_default": boolean;
    "rate_limit_rpm": number;
    "custom_headers": { [_ in string]?: string };
    "max_retries": number;
    "timeout_seconds": number;
    "reasoning_effort": string;

    /** Creates a new LLMConfigDTO instance. */
    constructor($$source: Partial<LLMConfigDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("provider_name" in $$source)) {
            this["provider_name"] = "";
        }
        if (!("api_url" in $$source)) {
            this["api_url"] = "";
        }
        if (!("masked_token" in $$source)) {
            this["masked_token"] = "";
        }
        if (!("has_token" in $$source)) {
            this["has_token"] = false;
        }
        if (!("model_name" in $$source)) {
            this["model_name"] = "";
        }
        if (!("is_active" in $$source)) {
            this["is_active"] = false;
        }
        if (!("is_default" in $$source)) {
            this["is_default"] = false;
        }
        if (!("rate_limit_rpm" in $$source)) {
            this["rate_limit_rpm"] = 0;
        }
        if (!("custom_headers" in $$source)) {
            this["custom_headers"] = {};
        }
        if (!("max_retries" in $$source)) {
            this["max_retries"] = 0;
        }
        if (!("timeout_seconds" in $$source)) {
            this["timeout_seconds"] = 0;
        }
        if (!("reasoning_effort" in $$source)) {
            this["reasoning_effort"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LLMConfigDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): LLMConfigDTO {
        const $$createField9_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("custom_headers" in $$parsedSource) {
            $$parsedSource["custom_headers"] = $$createField9_0($$parsedSource["custom_headers"]);
        }
        return new LLMConfigDTO($$parsedSource as Partial<LLMConfigDTO>);
    }
}

/**
 * LearnResultDTO conveys rules and few-shots inferred from user edits via /learn.
 */
export class LearnResultDTO {
    "success": boolean;
    "rules_learned": string[];
    "few_shots_learned": number;
    "summary": string;
    "target_skill_id": string;

    /** Creates a new LearnResultDTO instance. */
    constructor($$source: Partial<LearnResultDTO> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("rules_learned" in $$source)) {
            this["rules_learned"] = [];
        }
        if (!("few_shots_learned" in $$source)) {
            this["few_shots_learned"] = 0;
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }
        if (!("target_skill_id" in $$source)) {
            this["target_skill_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LearnResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): LearnResultDTO {
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rules_learned" in $$parsedSource) {
            $$parsedSource["rules_learned"] = $$createField1_0($$parsedSource["rules_learned"]);
        }
        return new LearnResultDTO($$parsedSource as Partial<LearnResultDTO>);
    }
}

/**
 * NovelClawMessageDTO represents a message or activity event within a thread.
 */
export class NovelClawMessageDTO {
    "id": string;
    "thread_id": string;
    "project_id": string;

    /**
     * "user" | "novelclaw" | "system" | "agent_stream"
     */
    "sender": string;

    /**
     * "user" | "assistant" | "system" | "tool"
     */
    "role": string;
    "content": string;
    "thinking_content"?: string;

    /**
     * e.g. "thinking", "tool_call", "action_dispatched"
     */
    "step_type"?: string;

    /**
     * "running" | "completed" | "error"
     */
    "step_status"?: string;
    "action_call_json"?: string;
    "is_collapsed": boolean;
    "is_archived_compact": boolean;
    "token_count": number;
    "created_at": string;

    /** Creates a new NovelClawMessageDTO instance. */
    constructor($$source: Partial<NovelClawMessageDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("thread_id" in $$source)) {
            this["thread_id"] = "";
        }
        if (!("project_id" in $$source)) {
            this["project_id"] = "";
        }
        if (!("sender" in $$source)) {
            this["sender"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("is_collapsed" in $$source)) {
            this["is_collapsed"] = false;
        }
        if (!("is_archived_compact" in $$source)) {
            this["is_archived_compact"] = false;
        }
        if (!("token_count" in $$source)) {
            this["token_count"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NovelClawMessageDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): NovelClawMessageDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NovelClawMessageDTO($$parsedSource as Partial<NovelClawMessageDTO>);
    }
}

/**
 * NovelClawThreadDTO represents a conversation thread in NovelClaw.
 */
export class NovelClawThreadDTO {
    "id": string;
    "project_id": string;
    "title": string;
    "is_main": boolean;
    "volume_index": number;
    "chapter_index": number;
    "created_at": string;
    "updated_at": string;
    "token_count"?: number;

    /** Creates a new NovelClawThreadDTO instance. */
    constructor($$source: Partial<NovelClawThreadDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("project_id" in $$source)) {
            this["project_id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("is_main" in $$source)) {
            this["is_main"] = false;
        }
        if (!("volume_index" in $$source)) {
            this["volume_index"] = 0;
        }
        if (!("chapter_index" in $$source)) {
            this["chapter_index"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NovelClawThreadDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): NovelClawThreadDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NovelClawThreadDTO($$parsedSource as Partial<NovelClawThreadDTO>);
    }
}

/**
 * PreviewStyleRequest carries text and style instructions to test LLM translation.
 */
export class PreviewStyleRequest {
    "project_id": string;
    "raw_content": string;
    "style_prompt": string;
    "source_lang": string;
    "target_lang": string;

    /** Creates a new PreviewStyleRequest instance. */
    constructor($$source: Partial<PreviewStyleRequest> = {}) {
        if (!("project_id" in $$source)) {
            this["project_id"] = "";
        }
        if (!("raw_content" in $$source)) {
            this["raw_content"] = "";
        }
        if (!("style_prompt" in $$source)) {
            this["style_prompt"] = "";
        }
        if (!("source_lang" in $$source)) {
            this["source_lang"] = "";
        }
        if (!("target_lang" in $$source)) {
            this["target_lang"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreviewStyleRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): PreviewStyleRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PreviewStyleRequest($$parsedSource as Partial<PreviewStyleRequest>);
    }
}

/**
 * PreviewStyleResponse returns the real-time LLM translated preview snippet.
 */
export class PreviewStyleResponse {
    "success": boolean;
    "translated_content": string;
    "model_used": string;
    "latency_ms": number;
    "error"?: string;

    /** Creates a new PreviewStyleResponse instance. */
    constructor($$source: Partial<PreviewStyleResponse> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("translated_content" in $$source)) {
            this["translated_content"] = "";
        }
        if (!("model_used" in $$source)) {
            this["model_used"] = "";
        }
        if (!("latency_ms" in $$source)) {
            this["latency_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreviewStyleResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): PreviewStyleResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PreviewStyleResponse($$parsedSource as Partial<PreviewStyleResponse>);
    }
}

/**
 * ProjectDTO represents a translation project for frontend display.
 */
export class ProjectDTO {
    "id": string;
    "title": string;
    "author": string;
    "source_lang": string;
    "target_lang": string;
    "original_format": string;
    "total_chapters": number;
    "style_guide": string;
    "style_name": string;
    "created_at": string;
    "updated_at": string;

    /** Creates a new ProjectDTO instance. */
    constructor($$source: Partial<ProjectDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("source_lang" in $$source)) {
            this["source_lang"] = "";
        }
        if (!("target_lang" in $$source)) {
            this["target_lang"] = "";
        }
        if (!("original_format" in $$source)) {
            this["original_format"] = "";
        }
        if (!("total_chapters" in $$source)) {
            this["total_chapters"] = 0;
        }
        if (!("style_guide" in $$source)) {
            this["style_guide"] = "";
        }
        if (!("style_name" in $$source)) {
            this["style_name"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectDTO($$parsedSource as Partial<ProjectDTO>);
    }
}

/**
 * RelationDTO represents an address term relation between two characters.
 */
export class RelationDTO {
    "id": string;
    "project_id": string;
    "from_char": string;
    "to_char": string;
    "call_as": string;
    "self_call_as": string;
    "since_chapter": number;
    "tone": string;
    "is_locked": boolean;
    "created_at": string;
    "updated_at": string;

    /** Creates a new RelationDTO instance. */
    constructor($$source: Partial<RelationDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("project_id" in $$source)) {
            this["project_id"] = "";
        }
        if (!("from_char" in $$source)) {
            this["from_char"] = "";
        }
        if (!("to_char" in $$source)) {
            this["to_char"] = "";
        }
        if (!("call_as" in $$source)) {
            this["call_as"] = "";
        }
        if (!("self_call_as" in $$source)) {
            this["self_call_as"] = "";
        }
        if (!("since_chapter" in $$source)) {
            this["since_chapter"] = 0;
        }
        if (!("tone" in $$source)) {
            this["tone"] = "";
        }
        if (!("is_locked" in $$source)) {
            this["is_locked"] = false;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RelationDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): RelationDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RelationDTO($$parsedSource as Partial<RelationDTO>);
    }
}

/**
 * RemoteGlossarySourceDTO represents an online dictionary source (e.g., community repositories on GitHub) for frontend display.
 */
export class RemoteGlossarySourceDTO {
    "id": string;
    "title": string;
    "genre": string;
    "description": string;
    "url": string;
    "format": string;
    "default_category": string;

    /** Creates a new RemoteGlossarySourceDTO instance. */
    constructor($$source: Partial<RemoteGlossarySourceDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("genre" in $$source)) {
            this["genre"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("format" in $$source)) {
            this["format"] = "";
        }
        if (!("default_category" in $$source)) {
            this["default_category"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteGlossarySourceDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): RemoteGlossarySourceDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RemoteGlossarySourceDTO($$parsedSource as Partial<RemoteGlossarySourceDTO>);
    }
}

/**
 * RenameProjectRequest provides payload for renaming a project.
 */
export class RenameProjectRequest {
    "id": string;
    "title": string;

    /** Creates a new RenameProjectRequest instance. */
    constructor($$source: Partial<RenameProjectRequest> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RenameProjectRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): RenameProjectRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RenameProjectRequest($$parsedSource as Partial<RenameProjectRequest>);
    }
}

/**
 * SaveLLMConfigRequest represents parameters for saving or updating an LLM configuration.
 */
export class SaveLLMConfigRequest {
    "id": string;
    "provider_name": string;
    "api_url": string;
    "token": string;
    "model_name": string;
    "is_active": boolean;
    "is_default": boolean;
    "rate_limit_rpm": number;
    "custom_headers": { [_ in string]?: string };
    "max_retries": number;
    "timeout_seconds": number;
    "reasoning_effort": string;

    /** Creates a new SaveLLMConfigRequest instance. */
    constructor($$source: Partial<SaveLLMConfigRequest> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("provider_name" in $$source)) {
            this["provider_name"] = "";
        }
        if (!("api_url" in $$source)) {
            this["api_url"] = "";
        }
        if (!("token" in $$source)) {
            this["token"] = "";
        }
        if (!("model_name" in $$source)) {
            this["model_name"] = "";
        }
        if (!("is_active" in $$source)) {
            this["is_active"] = false;
        }
        if (!("is_default" in $$source)) {
            this["is_default"] = false;
        }
        if (!("rate_limit_rpm" in $$source)) {
            this["rate_limit_rpm"] = 0;
        }
        if (!("custom_headers" in $$source)) {
            this["custom_headers"] = {};
        }
        if (!("max_retries" in $$source)) {
            this["max_retries"] = 0;
        }
        if (!("timeout_seconds" in $$source)) {
            this["timeout_seconds"] = 0;
        }
        if (!("reasoning_effort" in $$source)) {
            this["reasoning_effort"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveLLMConfigRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveLLMConfigRequest {
        const $$createField8_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("custom_headers" in $$parsedSource) {
            $$parsedSource["custom_headers"] = $$createField8_0($$parsedSource["custom_headers"]);
        }
        return new SaveLLMConfigRequest($$parsedSource as Partial<SaveLLMConfigRequest>);
    }
}

/**
 * ScanWorldResponse returns the outcome of an autonomous world scan.
 */
export class ScanWorldResponse {
    "success": boolean;
    "inferred_genre": string;
    "categories_added": number;
    "entries_added": number;
    "summary_report": string;
    "errors"?: string[];

    /** Creates a new ScanWorldResponse instance. */
    constructor($$source: Partial<ScanWorldResponse> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("inferred_genre" in $$source)) {
            this["inferred_genre"] = "";
        }
        if (!("categories_added" in $$source)) {
            this["categories_added"] = 0;
        }
        if (!("entries_added" in $$source)) {
            this["entries_added"] = 0;
        }
        if (!("summary_report" in $$source)) {
            this["summary_report"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScanWorldResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): ScanWorldResponse {
        const $$createField5_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField5_0($$parsedSource["errors"]);
        }
        return new ScanWorldResponse($$parsedSource as Partial<ScanWorldResponse>);
    }
}

/**
 * SelectiveContextDTO contains the filtered characters, relations, and glossary for a chunk.
 */
export class SelectiveContextDTO {
    "active_entities": EntityDTO[];
    "active_relations": RelationDTO[];
    "active_glossary": GlossaryTermDTO[];
    "formatted_prompt": string;

    /** Creates a new SelectiveContextDTO instance. */
    constructor($$source: Partial<SelectiveContextDTO> = {}) {
        if (!("active_entities" in $$source)) {
            this["active_entities"] = [];
        }
        if (!("active_relations" in $$source)) {
            this["active_relations"] = [];
        }
        if (!("active_glossary" in $$source)) {
            this["active_glossary"] = [];
        }
        if (!("formatted_prompt" in $$source)) {
            this["formatted_prompt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SelectiveContextDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SelectiveContextDTO {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("active_entities" in $$parsedSource) {
            $$parsedSource["active_entities"] = $$createField0_0($$parsedSource["active_entities"]);
        }
        if ("active_relations" in $$parsedSource) {
            $$parsedSource["active_relations"] = $$createField1_0($$parsedSource["active_relations"]);
        }
        if ("active_glossary" in $$parsedSource) {
            $$parsedSource["active_glossary"] = $$createField2_0($$parsedSource["active_glossary"]);
        }
        return new SelectiveContextDTO($$parsedSource as Partial<SelectiveContextDTO>);
    }
}

/**
 * SendNovelClawMessageRequest represents parameters to send a message to NovelClaw.
 */
export class SendNovelClawMessageRequest {
    "thread_id": string;
    "project_id": string;
    "content": string;

    /** Creates a new SendNovelClawMessageRequest instance. */
    constructor($$source: Partial<SendNovelClawMessageRequest> = {}) {
        if (!("thread_id" in $$source)) {
            this["thread_id"] = "";
        }
        if (!("project_id" in $$source)) {
            this["project_id"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SendNovelClawMessageRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SendNovelClawMessageRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SendNovelClawMessageRequest($$parsedSource as Partial<SendNovelClawMessageRequest>);
    }
}

/**
 * SkillDTO transfers a modular skill's status, rules, and token consumption to the frontend.
 */
export class SkillDTO {
    "id": string;
    "name": string;
    "description": string;
    "category": string;
    "estimated_token_weight": number;
    "weight_badge": string;
    "is_enabled": boolean;
    "system_prompt_template": string;
    "prohibited_rules": string[];
    "custom_rules": string;
    "few_shots": FewShotExampleDTO[];

    /** Creates a new SkillDTO instance. */
    constructor($$source: Partial<SkillDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("category" in $$source)) {
            this["category"] = "";
        }
        if (!("estimated_token_weight" in $$source)) {
            this["estimated_token_weight"] = 0;
        }
        if (!("weight_badge" in $$source)) {
            this["weight_badge"] = "";
        }
        if (!("is_enabled" in $$source)) {
            this["is_enabled"] = false;
        }
        if (!("system_prompt_template" in $$source)) {
            this["system_prompt_template"] = "";
        }
        if (!("prohibited_rules" in $$source)) {
            this["prohibited_rules"] = [];
        }
        if (!("custom_rules" in $$source)) {
            this["custom_rules"] = "";
        }
        if (!("few_shots" in $$source)) {
            this["few_shots"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SkillDTO {
        const $$createField8_0 = $$createType4;
        const $$createField10_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("prohibited_rules" in $$parsedSource) {
            $$parsedSource["prohibited_rules"] = $$createField8_0($$parsedSource["prohibited_rules"]);
        }
        if ("few_shots" in $$parsedSource) {
            $$parsedSource["few_shots"] = $$createField10_0($$parsedSource["few_shots"]);
        }
        return new SkillDTO($$parsedSource as Partial<SkillDTO>);
    }
}

/**
 * SkillPresetDTO represents a pre-configured bundle of skills for quick 1-click toggling.
 */
export class SkillPresetDTO {
    "id": string;
    "name": string;
    "description": string;
    "active_skill_ids": string[];
    "total_estimated_tokens": number;
    "active_skill_count": number;

    /** Creates a new SkillPresetDTO instance. */
    constructor($$source: Partial<SkillPresetDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("active_skill_ids" in $$source)) {
            this["active_skill_ids"] = [];
        }
        if (!("total_estimated_tokens" in $$source)) {
            this["total_estimated_tokens"] = 0;
        }
        if (!("active_skill_count" in $$source)) {
            this["active_skill_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillPresetDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SkillPresetDTO {
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("active_skill_ids" in $$parsedSource) {
            $$parsedSource["active_skill_ids"] = $$createField3_0($$parsedSource["active_skill_ids"]);
        }
        return new SkillPresetDTO($$parsedSource as Partial<SkillPresetDTO>);
    }
}

/**
 * SoulDTO represents the AI coworker companion persona and emotional state.
 */
export class SoulDTO {
    "id": string;
    "name": string;
    "avatar": string;
    "title": string;
    "archetype": string;
    "description": string;
    "greeting": string;
    "on_confused": string;
    "on_success": string;
    "system_tone": string;
    "current_mood": string;
    "system_prompt_addon": string;
    "is_default": boolean;

    /** Creates a new SoulDTO instance. */
    constructor($$source: Partial<SoulDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("avatar" in $$source)) {
            this["avatar"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("archetype" in $$source)) {
            this["archetype"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("greeting" in $$source)) {
            this["greeting"] = "";
        }
        if (!("on_confused" in $$source)) {
            this["on_confused"] = "";
        }
        if (!("on_success" in $$source)) {
            this["on_success"] = "";
        }
        if (!("system_tone" in $$source)) {
            this["system_tone"] = "";
        }
        if (!("current_mood" in $$source)) {
            this["current_mood"] = "";
        }
        if (!("system_prompt_addon" in $$source)) {
            this["system_prompt_addon"] = "";
        }
        if (!("is_default" in $$source)) {
            this["is_default"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SoulDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SoulDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SoulDTO($$parsedSource as Partial<SoulDTO>);
    }
}

/**
 * StartBenchmarkRequest contains parameters to run a comparative benchmark.
 */
export class StartBenchmarkRequest {
    "project_id": string;
    "chapter_indices": number[];
    "modes": string[];

    /** Creates a new StartBenchmarkRequest instance. */
    constructor($$source: Partial<StartBenchmarkRequest> = {}) {
        if (!("project_id" in $$source)) {
            this["project_id"] = "";
        }
        if (!("chapter_indices" in $$source)) {
            this["chapter_indices"] = [];
        }
        if (!("modes" in $$source)) {
            this["modes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartBenchmarkRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): StartBenchmarkRequest {
        const $$createField1_0 = $$createType15;
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("chapter_indices" in $$parsedSource) {
            $$parsedSource["chapter_indices"] = $$createField1_0($$parsedSource["chapter_indices"]);
        }
        if ("modes" in $$parsedSource) {
            $$parsedSource["modes"] = $$createField2_0($$parsedSource["modes"]);
        }
        return new StartBenchmarkRequest($$parsedSource as Partial<StartBenchmarkRequest>);
    }
}

/**
 * StartTranslationRequest contains parameters to begin translating a chapter.
 */
export class StartTranslationRequest {
    "project_id": string;
    "chapter_index": number;
    "options": TranslationOptionsDTO;

    /** Creates a new StartTranslationRequest instance. */
    constructor($$source: Partial<StartTranslationRequest> = {}) {
        if (!("project_id" in $$source)) {
            this["project_id"] = "";
        }
        if (!("chapter_index" in $$source)) {
            this["chapter_index"] = 0;
        }
        if (!("options" in $$source)) {
            this["options"] = (new TranslationOptionsDTO());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartTranslationRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): StartTranslationRequest {
        const $$createField2_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField2_0($$parsedSource["options"]);
        }
        return new StartTranslationRequest($$parsedSource as Partial<StartTranslationRequest>);
    }
}

/**
 * SteerActionRequest conveys emergency control or dynamic style overrides from the UI.
 */
export class SteerActionRequest {
    "job_id": string;
    "project_id"?: string;

    /**
     * "soft_stop", "hard_abort", "style_patch"
     */
    "action": string;
    "patch_value"?: string;

    /** Creates a new SteerActionRequest instance. */
    constructor($$source: Partial<SteerActionRequest> = {}) {
        if (!("job_id" in $$source)) {
            this["job_id"] = "";
        }
        if (!("action" in $$source)) {
            this["action"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SteerActionRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SteerActionRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SteerActionRequest($$parsedSource as Partial<SteerActionRequest>);
    }
}

/**
 * SteerActionResultDTO provides immediate feedback for a steering or abort command.
 */
export class SteerActionResultDTO {
    "success": boolean;
    "message": string;
    "current_mood": string;

    /** Creates a new SteerActionResultDTO instance. */
    constructor($$source: Partial<SteerActionResultDTO> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("current_mood" in $$source)) {
            this["current_mood"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SteerActionResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SteerActionResultDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SteerActionResultDTO($$parsedSource as Partial<SteerActionResultDTO>);
    }
}

/**
 * TestConnectionRequest conveys credentials to test with an LLM provider endpoint.
 */
export class TestConnectionRequest {
    "api_url": string;
    "token": string;
    "model_name": string;
    "config_id"?: string;

    /** Creates a new TestConnectionRequest instance. */
    constructor($$source: Partial<TestConnectionRequest> = {}) {
        if (!("api_url" in $$source)) {
            this["api_url"] = "";
        }
        if (!("token" in $$source)) {
            this["token"] = "";
        }
        if (!("model_name" in $$source)) {
            this["model_name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestConnectionRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): TestConnectionRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TestConnectionRequest($$parsedSource as Partial<TestConnectionRequest>);
    }
}

/**
 * TestConnectionResponse reports the result and latency of the ping check.
 */
export class TestConnectionResponse {
    "success": boolean;
    "latency_ms": number;
    "message": string;
    "model_found"?: string;

    /** Creates a new TestConnectionResponse instance. */
    constructor($$source: Partial<TestConnectionResponse> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("latency_ms" in $$source)) {
            this["latency_ms"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestConnectionResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): TestConnectionResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TestConnectionResponse($$parsedSource as Partial<TestConnectionResponse>);
    }
}

/**
 * TranslationOptionsDTO defines frontend options for selecting translation modes.
 */
export class TranslationOptionsDTO {
    "mode": string;
    "concurrency": number;
    "critic_model": string;
    "polish_model": string;
    "timeout_seconds": number;
    "max_retries": number;
    "enable_hot_patch": boolean;
    "enable_r19": boolean;
    "enable_agentic_rag": boolean;
    "max_tool_iterations": number;
    "decision_mode": string;
    "style_guide"?: string;
    "thinking_effort"?: string;

    /** Creates a new TranslationOptionsDTO instance. */
    constructor($$source: Partial<TranslationOptionsDTO> = {}) {
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("concurrency" in $$source)) {
            this["concurrency"] = 0;
        }
        if (!("critic_model" in $$source)) {
            this["critic_model"] = "";
        }
        if (!("polish_model" in $$source)) {
            this["polish_model"] = "";
        }
        if (!("timeout_seconds" in $$source)) {
            this["timeout_seconds"] = 0;
        }
        if (!("max_retries" in $$source)) {
            this["max_retries"] = 0;
        }
        if (!("enable_hot_patch" in $$source)) {
            this["enable_hot_patch"] = false;
        }
        if (!("enable_r19" in $$source)) {
            this["enable_r19"] = false;
        }
        if (!("enable_agentic_rag" in $$source)) {
            this["enable_agentic_rag"] = false;
        }
        if (!("max_tool_iterations" in $$source)) {
            this["max_tool_iterations"] = 0;
        }
        if (!("decision_mode" in $$source)) {
            this["decision_mode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TranslationOptionsDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): TranslationOptionsDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TranslationOptionsDTO($$parsedSource as Partial<TranslationOptionsDTO>);
    }
}

/**
 * UpdateChapterInlineRequest provides payload for manual in-line human editing.
 */
export class UpdateChapterInlineRequest {
    "id": string;
    "translated_content": string;
    "status"?: string;

    /** Creates a new UpdateChapterInlineRequest instance. */
    constructor($$source: Partial<UpdateChapterInlineRequest> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("translated_content" in $$source)) {
            this["translated_content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateChapterInlineRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateChapterInlineRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateChapterInlineRequest($$parsedSource as Partial<UpdateChapterInlineRequest>);
    }
}

/**
 * UpdateProjectLanguagesRequest provides payload for updating source and target languages of a project.
 */
export class UpdateProjectLanguagesRequest {
    "id": string;
    "source_lang": string;
    "target_lang": string;

    /** Creates a new UpdateProjectLanguagesRequest instance. */
    constructor($$source: Partial<UpdateProjectLanguagesRequest> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("source_lang" in $$source)) {
            this["source_lang"] = "";
        }
        if (!("target_lang" in $$source)) {
            this["target_lang"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateProjectLanguagesRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateProjectLanguagesRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateProjectLanguagesRequest($$parsedSource as Partial<UpdateProjectLanguagesRequest>);
    }
}

/**
 * UpdateProjectStyleRequest provides payload for updating custom or scouted style guide of a project.
 */
export class UpdateProjectStyleRequest {
    "id": string;
    "style_name": string;
    "style_guide": string;

    /** Creates a new UpdateProjectStyleRequest instance. */
    constructor($$source: Partial<UpdateProjectStyleRequest> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("style_name" in $$source)) {
            this["style_name"] = "";
        }
        if (!("style_guide" in $$source)) {
            this["style_guide"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateProjectStyleRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateProjectStyleRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateProjectStyleRequest($$parsedSource as Partial<UpdateProjectStyleRequest>);
    }
}

/**
 * UpsertEntityRequest contains parameters for creating or updating an entity node.
 */
export class UpsertEntityRequest {
    "id": string;
    "project_id": string;
    "name": string;
    "aliases": string[];
    "category": string;
    "gender": string;
    "role": string;
    "first_seen_chapter": number;
    "metadata": { [_ in string]?: any };

    /** Creates a new UpsertEntityRequest instance. */
    constructor($$source: Partial<UpsertEntityRequest> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("project_id" in $$source)) {
            this["project_id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("aliases" in $$source)) {
            this["aliases"] = [];
        }
        if (!("category" in $$source)) {
            this["category"] = "";
        }
        if (!("gender" in $$source)) {
            this["gender"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("first_seen_chapter" in $$source)) {
            this["first_seen_chapter"] = 0;
        }
        if (!("metadata" in $$source)) {
            this["metadata"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpsertEntityRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): UpsertEntityRequest {
        const $$createField3_0 = $$createType4;
        const $$createField8_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("aliases" in $$parsedSource) {
            $$parsedSource["aliases"] = $$createField3_0($$parsedSource["aliases"]);
        }
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField8_0($$parsedSource["metadata"]);
        }
        return new UpsertEntityRequest($$parsedSource as Partial<UpsertEntityRequest>);
    }
}

/**
 * UpsertGlossaryTermRequest contains parameters for creating or updating a glossary term.
 */
export class UpsertGlossaryTermRequest {
    "id": string;
    "project_id": string;
    "source_term": string;
    "target_term": string;
    "category": string;

    /** Creates a new UpsertGlossaryTermRequest instance. */
    constructor($$source: Partial<UpsertGlossaryTermRequest> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("project_id" in $$source)) {
            this["project_id"] = "";
        }
        if (!("source_term" in $$source)) {
            this["source_term"] = "";
        }
        if (!("target_term" in $$source)) {
            this["target_term"] = "";
        }
        if (!("category" in $$source)) {
            this["category"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpsertGlossaryTermRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): UpsertGlossaryTermRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpsertGlossaryTermRequest($$parsedSource as Partial<UpsertGlossaryTermRequest>);
    }
}

/**
 * UpsertRelationRequest contains parameters for creating or updating a character relation.
 */
export class UpsertRelationRequest {
    "id": string;
    "project_id": string;
    "from_char": string;
    "to_char": string;
    "call_as": string;
    "self_call_as": string;
    "since_chapter": number;
    "tone": string;
    "is_locked"?: boolean;

    /** Creates a new UpsertRelationRequest instance. */
    constructor($$source: Partial<UpsertRelationRequest> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("project_id" in $$source)) {
            this["project_id"] = "";
        }
        if (!("from_char" in $$source)) {
            this["from_char"] = "";
        }
        if (!("to_char" in $$source)) {
            this["to_char"] = "";
        }
        if (!("call_as" in $$source)) {
            this["call_as"] = "";
        }
        if (!("self_call_as" in $$source)) {
            this["self_call_as"] = "";
        }
        if (!("since_chapter" in $$source)) {
            this["since_chapter"] = 0;
        }
        if (!("tone" in $$source)) {
            this["tone"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpsertRelationRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): UpsertRelationRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpsertRelationRequest($$parsedSource as Partial<UpsertRelationRequest>);
    }
}

/**
 * UpsertVoiceRequest registers or updates a character voice profile.
 */
export class UpsertVoiceRequest {
    "project_id": string;
    "character_id": string;
    "name": string;
    "aliases": string[];
    "voice_tone": string;
    "dialogue_rules": string[];
    "catchphrases": string[];

    /** Creates a new UpsertVoiceRequest instance. */
    constructor($$source: Partial<UpsertVoiceRequest> = {}) {
        if (!("project_id" in $$source)) {
            this["project_id"] = "";
        }
        if (!("character_id" in $$source)) {
            this["character_id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("aliases" in $$source)) {
            this["aliases"] = [];
        }
        if (!("voice_tone" in $$source)) {
            this["voice_tone"] = "";
        }
        if (!("dialogue_rules" in $$source)) {
            this["dialogue_rules"] = [];
        }
        if (!("catchphrases" in $$source)) {
            this["catchphrases"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpsertVoiceRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): UpsertVoiceRequest {
        const $$createField3_0 = $$createType4;
        const $$createField5_0 = $$createType4;
        const $$createField6_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("aliases" in $$parsedSource) {
            $$parsedSource["aliases"] = $$createField3_0($$parsedSource["aliases"]);
        }
        if ("dialogue_rules" in $$parsedSource) {
            $$parsedSource["dialogue_rules"] = $$createField5_0($$parsedSource["dialogue_rules"]);
        }
        if ("catchphrases" in $$parsedSource) {
            $$parsedSource["catchphrases"] = $$createField6_0($$parsedSource["catchphrases"]);
        }
        return new UpsertVoiceRequest($$parsedSource as Partial<UpsertVoiceRequest>);
    }
}

/**
 * UpsertWorldCategoryRequest holds inputs to create or update a category.
 */
export class UpsertWorldCategoryRequest {
    "id"?: string;
    "project_id": string;
    "slug": string;
    "name": string;
    "icon": string;
    "description": string;
    "display_order": number;

    /** Creates a new UpsertWorldCategoryRequest instance. */
    constructor($$source: Partial<UpsertWorldCategoryRequest> = {}) {
        if (!("project_id" in $$source)) {
            this["project_id"] = "";
        }
        if (!("slug" in $$source)) {
            this["slug"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("display_order" in $$source)) {
            this["display_order"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpsertWorldCategoryRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): UpsertWorldCategoryRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpsertWorldCategoryRequest($$parsedSource as Partial<UpsertWorldCategoryRequest>);
    }
}

/**
 * UpsertWorldEntryRequest holds inputs to create or update an entry.
 */
export class UpsertWorldEntryRequest {
    "id"?: string;
    "project_id": string;
    "category_id": string;
    "name": string;
    "aliases": string[];
    "summary": string;
    "full_description": string;
    "attributes": { [_ in string]?: string };
    "source_chapter_index": number;
    "is_verified": boolean;

    /** Creates a new UpsertWorldEntryRequest instance. */
    constructor($$source: Partial<UpsertWorldEntryRequest> = {}) {
        if (!("project_id" in $$source)) {
            this["project_id"] = "";
        }
        if (!("category_id" in $$source)) {
            this["category_id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("aliases" in $$source)) {
            this["aliases"] = [];
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }
        if (!("full_description" in $$source)) {
            this["full_description"] = "";
        }
        if (!("attributes" in $$source)) {
            this["attributes"] = {};
        }
        if (!("source_chapter_index" in $$source)) {
            this["source_chapter_index"] = 0;
        }
        if (!("is_verified" in $$source)) {
            this["is_verified"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpsertWorldEntryRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): UpsertWorldEntryRequest {
        const $$createField4_0 = $$createType4;
        const $$createField7_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("aliases" in $$parsedSource) {
            $$parsedSource["aliases"] = $$createField4_0($$parsedSource["aliases"]);
        }
        if ("attributes" in $$parsedSource) {
            $$parsedSource["attributes"] = $$createField7_0($$parsedSource["attributes"]);
        }
        return new UpsertWorldEntryRequest($$parsedSource as Partial<UpsertWorldEntryRequest>);
    }
}

/**
 * WorldCategoryDTO represents a dynamic classification group for world lore.
 */
export class WorldCategoryDTO {
    "id": string;
    "project_id": string;
    "slug": string;
    "name": string;
    "icon": string;
    "description": string;
    "display_order": number;
    "entry_count": number;
    "created_at": string;

    /** Creates a new WorldCategoryDTO instance. */
    constructor($$source: Partial<WorldCategoryDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("project_id" in $$source)) {
            this["project_id"] = "";
        }
        if (!("slug" in $$source)) {
            this["slug"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("display_order" in $$source)) {
            this["display_order"] = 0;
        }
        if (!("entry_count" in $$source)) {
            this["entry_count"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorldCategoryDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorldCategoryDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorldCategoryDTO($$parsedSource as Partial<WorldCategoryDTO>);
    }
}

/**
 * WorldEntryDTO represents a specific Lorebook entity in the World Bible.
 */
export class WorldEntryDTO {
    "id": string;
    "project_id": string;
    "category_id": string;
    "category_slug": string;
    "category_name": string;
    "name": string;
    "aliases": string[];
    "summary": string;
    "full_description": string;
    "attributes": { [_ in string]?: string };

    /**
     * 'ai_scan' | 'manual' | 'chat_command'
     */
    "discovered_by": string;
    "source_chapter_index": number;
    "is_verified": boolean;
    "created_at": string;
    "updated_at": string;

    /** Creates a new WorldEntryDTO instance. */
    constructor($$source: Partial<WorldEntryDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("project_id" in $$source)) {
            this["project_id"] = "";
        }
        if (!("category_id" in $$source)) {
            this["category_id"] = "";
        }
        if (!("category_slug" in $$source)) {
            this["category_slug"] = "";
        }
        if (!("category_name" in $$source)) {
            this["category_name"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("aliases" in $$source)) {
            this["aliases"] = [];
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }
        if (!("full_description" in $$source)) {
            this["full_description"] = "";
        }
        if (!("attributes" in $$source)) {
            this["attributes"] = {};
        }
        if (!("discovered_by" in $$source)) {
            this["discovered_by"] = "";
        }
        if (!("source_chapter_index" in $$source)) {
            this["source_chapter_index"] = 0;
        }
        if (!("is_verified" in $$source)) {
            this["is_verified"] = false;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorldEntryDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorldEntryDTO {
        const $$createField6_0 = $$createType4;
        const $$createField9_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("aliases" in $$parsedSource) {
            $$parsedSource["aliases"] = $$createField6_0($$parsedSource["aliases"]);
        }
        if ("attributes" in $$parsedSource) {
            $$parsedSource["attributes"] = $$createField9_0($$parsedSource["attributes"]);
        }
        return new WorldEntryDTO($$parsedSource as Partial<WorldEntryDTO>);
    }
}

// Private type creation functions
const $$createType0 = EntityDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = RelationDTO.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = ProjectDTO.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = BenchmarkMetricsDTO.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Map($Create.Any, $Create.Any);
const $$createType10 = $Create.Map($Create.Any, $Create.Any);
const $$createType11 = GlossaryTermDTO.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = FewShotExampleDTO.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = $Create.Array($Create.Any);
const $$createType16 = TranslationOptionsDTO.createFrom;
