// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppendBookRequest specifies a book file to append as a new volume to an existing project/series.
 */
export interface AppendBookRequest {
    "project_id": string;
    "file_path": string;
    "vol_name"?: string;
}

/**
 * AutoScanRequest specifies parameters for AI auto-extracting characters and relations.
 */
export interface AutoScanRequest {
    "project_id": string;
    "chapter_index"?: number;

    /**
     * "volume" (default), "pre_scan", "current_chapter", "all"
     */
    "scan_mode": string;
    "volume"?: string;
}

/**
 * AutoScanResultDTO contains the results of AI auto-scanning entities and relations.
 */
export interface AutoScanResultDTO {
    "success": boolean;
    "message": string;
    "entities_found": number;
    "relations_found": number;
    "duration_ms": number;
    "volume_scanned"?: string;
    "effective_chapter": number;
    "discovered_entities": EntityDTO[] | null;
    "discovered_relations": RelationDTO[] | null;
}

/**
 * AutoScoutStyleRequest requests autonomous literary style analysis across opening novel chapters.
 */
export interface AutoScoutStyleRequest {
    "project_id": string;
    "source_lang": string;
    "target_lang": string;
}

/**
 * AutoScoutStyleResponse returns the LLM's tailored literary style profile.
 */
export interface AutoScoutStyleResponse {
    "success": boolean;
    "style_name": string;
    "style_description": string;
    "style_prompt": string;
    "analysis_notes": string;
    "sample_excerpt": string;
    "sample_translated": string;
    "model_used": string;
    "latency_ms": number;
    "chapters_sampled": number;
    "error"?: string;
}

/**
 * BatchImportBookRequest specifies multiple files to ingest into the studio.
 */
export interface BatchImportBookRequest {
    "file_paths": string[] | null;
    "source_lang"?: string;
    "target_lang"?: string;
    "as_series": boolean;
    "series_name"?: string;
}

/**
 * BatchImportResultDTO summarizes the results of batch file ingestion.
 */
export interface BatchImportResultDTO {
    "total_files": number;
    "success_count": number;
    "failed_count": number;
    "projects": ProjectDTO[] | null;
    "error_messages"?: string[] | null;
}

/**
 * BenchmarkMetricsDTO represents performance data for a specific translation mode.
 */
export interface BenchmarkMetricsDTO {
    "mode": string;
    "chapters_count": number;
    "total_runes": number;
    "duration_ms": number;
    "runes_per_second": number;
    "tokens_per_second": number;
    "prompt_tokens": number;
    "completion_tokens": number;
    "total_tokens": number;
    "reasoning_tokens": number;
    "estimated_cost_usd": number;
    "pronoun_consistency_score": number;
    "revised_count": number;
}

/**
 * BenchmarkReportDTO summarizes comparative benchmarks across modes.
 */
export interface BenchmarkReportDTO {
    "project_id": string;
    "timestamp": string;
    "results": BenchmarkMetricsDTO[] | null;
    "markdown_report": string;
}

/**
 * ChapterDTO represents an individual chapter for the workspace UI.
 */
export interface ChapterDTO {
    "id": string;
    "project_id": string;
    "chapter_index": number;
    "title": string;
    "content_path": string;
    "raw_content": string;
    "translated_content": string;
    "status": string;
    "created_at": string;
    "updated_at": string;
}

/**
 * CharacterVoiceDTO conveys persona and dialogue style rules for character voice prompting.
 */
export interface CharacterVoiceDTO {
    "character_id": string;
    "name": string;
    "aliases": string[] | null;
    "voice_tone": string;
    "dialogue_rules": string[] | null;
    "catchphrases": string[] | null;
}

/**
 * CompactThreadResponse contains results after compacting a thread.
 */
export interface CompactThreadResponse {
    "thread_id": string;
    "original_tokens": number;
    "compacted_tokens": number;
    "archived_messages": number;
    "summary_notice": string;
}

/**
 * CreateProjectRequest contains parameters for creating a new translation project.
 */
export interface CreateProjectRequest {
    "id": string;
    "title": string;
    "author": string;
    "source_lang": string;
    "target_lang": string;
    "original_format": string;
    "total_chapters": number;
}

/**
 * CreateSubThreadRequest represents parameters to create a new sub-chat thread.
 */
export interface CreateSubThreadRequest {
    "project_id": string;
    "title": string;
    "volume_index": number;
    "chapter_index": number;
}

/**
 * DownloadGlossaryRequest contains parameters for downloading and importing a remote dictionary file.
 */
export interface DownloadGlossaryRequest {
    "project_id": string;
    "url": string;

    /**
     * "vietphrase" | "tsv" | "json"
     */
    "format": string;
    "default_category": string;
}

/**
 * EntityDTO represents a character or entity node in the story graph.
 */
export interface EntityDTO {
    "id": string;
    "project_id": string;
    "name": string;
    "aliases": string[] | null;
    "category": string;
    "gender": string;
    "role": string;
    "first_seen_chapter": number;
    "metadata": { [_ in string]?: any } | null;
}

/**
 * ExecutionTelemetryDTO represents quantitative telemetry after translation completes.
 */
export interface ExecutionTelemetryDTO {
    "mode": string;
    "duration_ms": number;
    "prompt_tokens": number;
    "completion_tokens": number;
    "total_tokens": number;
    "reasoning_tokens": number;
    "revised_count": number;
    "tool_calls_count": number;
    "total_runes": number;
    "runes_per_second": number;
    "tokens_per_second": number;
    "estimated_cost_usd": number;
}

/**
 * ExportBundleRequest specifies the project ID and destination path for a .neko bundle.
 */
export interface ExportBundleRequest {
    "project_id": string;
    "output_path": string;
}

/**
 * ExportEbookRequest defines the parameters for synthesizing an ebook.
 */
export interface ExportEbookRequest {
    "project_id": string;
    "target_format": string;
    "output_path": string;
    "custom_title"?: string;
    "custom_author"?: string;
    "cover_image_path"?: string;
    "use_translated_only": boolean;
    "volume"?: string;
}

/**
 * ExportResultDTO represents the outcome of an export or bundle packaging operation.
 */
export interface ExportResultDTO {
    "output_path": string;
    "format": string;
    "file_size_bytes": number;
    "chapter_count": number;
    "duration_ms": number;
}

/**
 * FewShotExampleDTO holds a demonstration pair for a skill.
 */
export interface FewShotExampleDTO {
    "input": string;
    "output": string;
    "note"?: string;
}

/**
 * FormatDescriptorDTO provides user-friendly metadata for each supported export format.
 */
export interface FormatDescriptorDTO {
    "format": string;
    "name": string;
    "extension": string;
    "description": string;
    "recommended_for": string;
}

/**
 * GlossaryTermDTO represents a terminology entry for frontend display.
 */
export interface GlossaryTermDTO {
    "id": string;
    "project_id": string;
    "source_term": string;
    "target_term": string;
    "category": string;
    "notes": string;
    "created_at": string;
}

/**
 * GraphReadinessDTO conveys whether the graph is ready and up-to-date for a specific chapter/volume.
 */
export interface GraphReadinessDTO {
    "is_ready": boolean;
    "project_id": string;
    "chapter_index": number;
    "volume_tag"?: string;
    "volume_start_chapter"?: number;
    "volume_end_chapter"?: number;
    "has_volume_scan": boolean;
    "volume_relations_count": number;
    "total_project_relations": number;
    "total_project_entities": number;
    "message": string;
}

/**
 * ImportBookRequest describes a book file to parse and ingest into a new project.
 */
export interface ImportBookRequest {
    "file_path": string;
    "project_id"?: string;
    "source_lang"?: string;
    "target_lang"?: string;
}

/**
 * InheritKnowledgeRequest specifies source and target project for copying universe knowledge.
 */
export interface InheritKnowledgeRequest {
    "source_project_id": string;
    "target_project_id": string;
}

/**
 * InheritKnowledgeResultDTO returns the count of copied items.
 */
export interface InheritKnowledgeResultDTO {
    "entities_count": number;
    "relations_count": number;
    "glossary_count": number;
    "success": boolean;
}

/**
 * LLMConfigDTO represents an LLM provider configuration with masked sensitive tokens.
 */
export interface LLMConfigDTO {
    "id": string;
    "provider_name": string;
    "api_url": string;
    "masked_token": string;
    "has_token": boolean;
    "model_name": string;
    "is_active": boolean;
    "is_default": boolean;
    "rate_limit_rpm": number;
    "custom_headers": { [_ in string]?: string } | null;
    "max_retries": number;
    "timeout_seconds": number;
    "reasoning_effort": string;
}

/**
 * LearnResultDTO conveys rules and few-shots inferred from user edits via /learn.
 */
export interface LearnResultDTO {
    "success": boolean;
    "rules_learned": string[] | null;
    "few_shots_learned": number;
    "summary": string;
    "target_skill_id": string;
}

/**
 * NovelClawMessageDTO represents a message or activity event within a thread.
 */
export interface NovelClawMessageDTO {
    "id": string;
    "thread_id": string;
    "project_id": string;

    /**
     * "user" | "novelclaw" | "system" | "agent_stream"
     */
    "sender": string;

    /**
     * "user" | "assistant" | "system" | "tool"
     */
    "role": string;
    "content": string;
    "thinking_content"?: string;

    /**
     * e.g. "thinking", "tool_call", "action_dispatched"
     */
    "step_type"?: string;

    /**
     * "running" | "completed" | "error"
     */
    "step_status"?: string;
    "action_call_json"?: string;
    "is_collapsed": boolean;
    "is_archived_compact": boolean;
    "token_count": number;
    "created_at": string;
}

/**
 * NovelClawThreadDTO represents a conversation thread in NovelClaw.
 */
export interface NovelClawThreadDTO {
    "id": string;
    "project_id": string;
    "title": string;
    "is_main": boolean;
    "volume_index": number;
    "chapter_index": number;
    "created_at": string;
    "updated_at": string;
    "token_count"?: number;
}

/**
 * PreviewStyleRequest carries text and style instructions to test LLM translation.
 */
export interface PreviewStyleRequest {
    "project_id": string;
    "raw_content": string;
    "style_prompt": string;
    "source_lang": string;
    "target_lang": string;
}

/**
 * PreviewStyleResponse returns the real-time LLM translated preview snippet.
 */
export interface PreviewStyleResponse {
    "success": boolean;
    "translated_content": string;
    "model_used": string;
    "latency_ms": number;
    "error"?: string;
}

/**
 * ProjectDTO represents a translation project for frontend display.
 */
export interface ProjectDTO {
    "id": string;
    "title": string;
    "author": string;
    "source_lang": string;
    "target_lang": string;
    "original_format": string;
    "total_chapters": number;
    "style_guide": string;
    "style_name": string;
    "created_at": string;
    "updated_at": string;
}

/**
 * RelationDTO represents an address term relation between two characters.
 */
export interface RelationDTO {
    "id": string;
    "project_id": string;
    "from_char": string;
    "to_char": string;
    "call_as": string;
    "self_call_as": string;
    "since_chapter": number;
    "tone": string;
    "is_locked": boolean;
    "created_at": string;
    "updated_at": string;
}

/**
 * RemoteGlossarySourceDTO represents an online dictionary source (e.g., community repositories on GitHub) for frontend display.
 */
export interface RemoteGlossarySourceDTO {
    "id": string;
    "title": string;
    "genre": string;
    "description": string;
    "url": string;
    "format": string;
    "default_category": string;
}

/**
 * RenameProjectRequest provides payload for renaming a project.
 */
export interface RenameProjectRequest {
    "id": string;
    "title": string;
}

/**
 * SaveLLMConfigRequest represents parameters for saving or updating an LLM configuration.
 */
export interface SaveLLMConfigRequest {
    "id": string;
    "provider_name": string;
    "api_url": string;
    "token": string;
    "model_name": string;
    "is_active": boolean;
    "is_default": boolean;
    "rate_limit_rpm": number;
    "custom_headers": { [_ in string]?: string } | null;
    "max_retries": number;
    "timeout_seconds": number;
    "reasoning_effort": string;
}

/**
 * ScanWorldResponse returns the outcome of an autonomous world scan.
 */
export interface ScanWorldResponse {
    "success": boolean;
    "inferred_genre": string;
    "categories_added": number;
    "entries_added": number;
    "summary_report": string;
    "errors"?: string[] | null;
}

/**
 * SelectiveContextDTO contains the filtered characters, relations, and glossary for a chunk.
 */
export interface SelectiveContextDTO {
    "active_entities": EntityDTO[] | null;
    "active_relations": RelationDTO[] | null;
    "active_glossary": GlossaryTermDTO[] | null;
    "formatted_prompt": string;
}

/**
 * SendNovelClawMessageRequest represents parameters to send a message to NovelClaw.
 */
export interface SendNovelClawMessageRequest {
    "thread_id": string;
    "project_id": string;
    "content": string;
}

/**
 * SkillDTO transfers a modular skill's status, rules, and token consumption to the frontend.
 */
export interface SkillDTO {
    "id": string;
    "name": string;
    "description": string;
    "category": string;
    "estimated_token_weight": number;
    "weight_badge": string;
    "is_enabled": boolean;
    "system_prompt_template": string;
    "prohibited_rules": string[] | null;
    "custom_rules": string;
    "few_shots": FewShotExampleDTO[] | null;
}

/**
 * SkillPresetDTO represents a pre-configured bundle of skills for quick 1-click toggling.
 */
export interface SkillPresetDTO {
    "id": string;
    "name": string;
    "description": string;
    "active_skill_ids": string[] | null;
    "total_estimated_tokens": number;
    "active_skill_count": number;
}

/**
 * SoulDTO represents the AI coworker companion persona and emotional state.
 */
export interface SoulDTO {
    "id": string;
    "name": string;
    "avatar": string;
    "title": string;
    "archetype": string;
    "description": string;
    "greeting": string;
    "on_confused": string;
    "on_success": string;
    "system_tone": string;
    "current_mood": string;
    "system_prompt_addon": string;
    "is_default": boolean;
}

/**
 * StartBenchmarkRequest contains parameters to run a comparative benchmark.
 */
export interface StartBenchmarkRequest {
    "project_id": string;
    "chapter_indices": number[] | null;
    "modes": string[] | null;
}

/**
 * StartTranslationRequest contains parameters to begin translating a chapter.
 */
export interface StartTranslationRequest {
    "project_id": string;
    "chapter_index": number;
    "options": TranslationOptionsDTO;
}

/**
 * SteerActionRequest conveys emergency control or dynamic style overrides from the UI.
 */
export interface SteerActionRequest {
    "job_id": string;
    "project_id"?: string;

    /**
     * "soft_stop", "hard_abort", "style_patch"
     */
    "action": string;
    "patch_value"?: string;
}

/**
 * SteerActionResultDTO provides immediate feedback for a steering or abort command.
 */
export interface SteerActionResultDTO {
    "success": boolean;
    "message": string;
    "current_mood": string;
}

/**
 * TestConnectionRequest conveys credentials to test with an LLM provider endpoint.
 */
export interface TestConnectionRequest {
    "api_url": string;
    "token": string;
    "model_name": string;
    "config_id"?: string;
}

/**
 * TestConnectionResponse reports the result and latency of the ping check.
 */
export interface TestConnectionResponse {
    "success": boolean;
    "latency_ms": number;
    "message": string;
    "model_found"?: string;
}

/**
 * TranslationOptionsDTO defines frontend options for selecting translation modes.
 */
export interface TranslationOptionsDTO {
    "mode": string;
    "concurrency": number;
    "critic_model": string;
    "polish_model": string;
    "timeout_seconds": number;
    "max_retries": number;
    "enable_hot_patch": boolean;
    "enable_r19": boolean;
    "enable_agentic_rag": boolean;
    "max_tool_iterations": number;
    "decision_mode": string;
    "style_guide"?: string;
    "thinking_effort"?: string;
}

/**
 * UpdateChapterInlineRequest provides payload for manual in-line human editing.
 */
export interface UpdateChapterInlineRequest {
    "id": string;
    "translated_content": string;
    "status"?: string;
}

/**
 * UpdateProjectLanguagesRequest provides payload for updating source and target languages of a project.
 */
export interface UpdateProjectLanguagesRequest {
    "id": string;
    "source_lang": string;
    "target_lang": string;
}

/**
 * UpdateProjectStyleRequest provides payload for updating custom or scouted style guide of a project.
 */
export interface UpdateProjectStyleRequest {
    "id": string;
    "style_name": string;
    "style_guide": string;
}

/**
 * UpsertEntityRequest contains parameters for creating or updating an entity node.
 */
export interface UpsertEntityRequest {
    "id": string;
    "project_id": string;
    "name": string;
    "aliases": string[] | null;
    "category": string;
    "gender": string;
    "role": string;
    "first_seen_chapter": number;
    "metadata": { [_ in string]?: any } | null;
}

/**
 * UpsertGlossaryTermRequest contains parameters for creating or updating a glossary term.
 */
export interface UpsertGlossaryTermRequest {
    "id": string;
    "project_id": string;
    "source_term": string;
    "target_term": string;
    "category": string;
}

/**
 * UpsertRelationRequest contains parameters for creating or updating a character relation.
 */
export interface UpsertRelationRequest {
    "id": string;
    "project_id": string;
    "from_char": string;
    "to_char": string;
    "call_as": string;
    "self_call_as": string;
    "since_chapter": number;
    "tone": string;
    "is_locked"?: boolean;
}

/**
 * UpsertVoiceRequest registers or updates a character voice profile.
 */
export interface UpsertVoiceRequest {
    "project_id": string;
    "character_id": string;
    "name": string;
    "aliases": string[] | null;
    "voice_tone": string;
    "dialogue_rules": string[] | null;
    "catchphrases": string[] | null;
}

/**
 * UpsertWorldCategoryRequest holds inputs to create or update a category.
 */
export interface UpsertWorldCategoryRequest {
    "id"?: string;
    "project_id": string;
    "slug": string;
    "name": string;
    "icon": string;
    "description": string;
    "display_order": number;
}

/**
 * UpsertWorldEntryRequest holds inputs to create or update an entry.
 */
export interface UpsertWorldEntryRequest {
    "id"?: string;
    "project_id": string;
    "category_id": string;
    "name": string;
    "aliases": string[] | null;
    "summary": string;
    "full_description": string;
    "attributes": { [_ in string]?: string } | null;
    "source_chapter_index": number;
    "is_verified": boolean;
}

/**
 * WorldCategoryDTO represents a dynamic classification group for world lore.
 */
export interface WorldCategoryDTO {
    "id": string;
    "project_id": string;
    "slug": string;
    "name": string;
    "icon": string;
    "description": string;
    "display_order": number;
    "entry_count": number;
    "created_at": string;
}

/**
 * WorldEntryDTO represents a specific Lorebook entity in the World Bible.
 */
export interface WorldEntryDTO {
    "id": string;
    "project_id": string;
    "category_id": string;
    "category_slug": string;
    "category_name": string;
    "name": string;
    "aliases": string[] | null;
    "summary": string;
    "full_description": string;
    "attributes": { [_ in string]?: string } | null;

    /**
     * 'ai_scan' | 'manual' | 'chat_command'
     */
    "discovered_by": string;
    "source_chapter_index": number;
    "is_verified": boolean;
    "created_at": string;
    "updated_at": string;
}
