// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ExportService coordinates ebook creation, packaging, and format inquiries for Wails v3.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dtos$0 from "../dtos/models.js";

/**
 * ExportEbook synthesizes an ebook file in the requested format.
 */
export function ExportEbook(req: dtos$0.ExportEbookRequest): $CancellablePromise<dtos$0.ExportResultDTO | null> {
    return $Call.ByID(3919235378, req);
}

/**
 * ExportProjectBundle packages all project database records and assets into a portable .neko file.
 */
export function ExportProjectBundle(req: dtos$0.ExportBundleRequest): $CancellablePromise<dtos$0.ExportResultDTO | null> {
    return $Call.ByID(2931067053, req);
}

/**
 * ListSupportedFormats returns all available ebook export formats with metadata.
 */
export function ListSupportedFormats(): $CancellablePromise<dtos$0.FormatDescriptorDTO[] | null> {
    return $Call.ByID(334680068);
}
