// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FSService provides native OS file dialogs and filesystem helpers for Wails v3.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * PickBookFile opens a native OS file dialog to select a single novel or ebook file.
 */
export function PickBookFile(): $CancellablePromise<string> {
    return $Call.ByID(3932006485);
}

/**
 * PickBookFiles opens a native OS file dialog to select multiple novel or ebook files.
 */
export function PickBookFiles(): $CancellablePromise<string[]> {
    return $Call.ByID(393196498).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * PickFolder opens a native OS folder picker dialog.
 */
export function PickFolder(): $CancellablePromise<string> {
    return $Call.ByID(855191078);
}

/**
 * ScanFolderForBooks finds all supported ebook and novel files in a given directory.
 */
export function ScanFolderForBooks(dirPath: string): $CancellablePromise<string[]> {
    return $Call.ByID(3380682557, dirPath).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
