// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GlossaryService exposes terminology and dictionary operations to Wails v3 frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dtos$0 from "../dtos/models.js";

/**
 * DeleteTerm deletes a glossary term by ID.
 */
export function DeleteTerm(id: string): $CancellablePromise<void> {
    return $Call.ByID(1968338565, id);
}

/**
 * DownloadAndImport fetches dictionary content from a remote URL (GitHub raw, Pastebin, custom link) and imports it into the project.
 */
export function DownloadAndImport(req: dtos$0.DownloadGlossaryRequest): $CancellablePromise<number> {
    return $Call.ByID(2281847388, req);
}

/**
 * ExportJSON exports glossary items as a JSON string.
 */
export function ExportJSON(projectID: string): $CancellablePromise<string> {
    return $Call.ByID(3543361916, projectID);
}

/**
 * ExportTSV exports glossary items as a TSV string.
 */
export function ExportTSV(projectID: string): $CancellablePromise<string> {
    return $Call.ByID(450247759, projectID);
}

/**
 * ImportJSON imports glossary items from a JSON string.
 */
export function ImportJSON(projectID: string, jsonContent: string): $CancellablePromise<number> {
    return $Call.ByID(3861604327, projectID, jsonContent);
}

/**
 * ImportPlainText imports glossary items from standard 'source=target' lines (Vietphrase / QuickTranslator format).
 */
export function ImportPlainText(projectID: string, content: string, defaultCategory: string): $CancellablePromise<number> {
    return $Call.ByID(3910215268, projectID, content, defaultCategory);
}

/**
 * ImportTSV imports glossary items from a TSV string.
 */
export function ImportTSV(projectID: string, tsvContent: string): $CancellablePromise<number> {
    return $Call.ByID(3504655886, projectID, tsvContent);
}

/**
 * ListRemoteSources returns all community online dictionary sources (e.g. GitHub repos) for frontend display.
 */
export function ListRemoteSources(): $CancellablePromise<dtos$0.RemoteGlossarySourceDTO[] | null> {
    return $Call.ByID(241397084);
}

/**
 * ListTerms lists all terms in a project's glossary as DTOs.
 */
export function ListTerms(projectID: string): $CancellablePromise<dtos$0.GlossaryTermDTO[] | null> {
    return $Call.ByID(1744182639, projectID);
}

/**
 * UpsertTerm inserts or updates a glossary term from a DTO request.
 */
export function UpsertTerm(req: dtos$0.UpsertGlossaryTermRequest): $CancellablePromise<void> {
    return $Call.ByID(4078345245, req);
}
