// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LLMService exposes LLM provider configuration, connection testing, and credential management to Wails v3 frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dtos$0 from "../dtos/models.js";

/**
 * DeleteConfig removes an LLM provider configuration by ID.
 */
export function DeleteConfig(id: string): $CancellablePromise<void> {
    return $Call.ByID(4211360404, id);
}

/**
 * GetDefaultConfig returns the active default LLM provider configuration with masked token as a DTO.
 */
export function GetDefaultConfig(): $CancellablePromise<dtos$0.LLMConfigDTO | null> {
    return $Call.ByID(1541586174).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListConfigs lists all active LLM configurations with masked tokens as DTOs.
 */
export function ListConfigs(): $CancellablePromise<dtos$0.LLMConfigDTO[]> {
    return $Call.ByID(4069433792).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SaveConfig saves an LLM provider configuration with AES-256-GCM encryption from a DTO request.
 */
export function SaveConfig(req: dtos$0.SaveLLMConfigRequest): $CancellablePromise<void> {
    return $Call.ByID(1368552758, req);
}

/**
 * SetDefaultConfig marks a specific LLM configuration as the default for translation runs.
 */
export function SetDefaultConfig(id: string): $CancellablePromise<void> {
    return $Call.ByID(1022628930, id);
}

/**
 * TestConnection sends a lightweight probe to verify connectivity and API key validity with the provider.
 */
export function TestConnection(req: dtos$0.TestConnectionRequest): $CancellablePromise<dtos$0.TestConnectionResponse | null> {
    return $Call.ByID(3826890153, req).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = dtos$0.LLMConfigDTO.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
const $$createType3 = dtos$0.TestConnectionResponse.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
