// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NovelClawService exposes NovelClaw Agentic chat, threads, and auto-compact to Wails v3 frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dtos$0 from "../dtos/models.js";

/**
 * ClearThread deletes all messages in a thread.
 */
export function ClearThread(threadID: string): $CancellablePromise<void> {
    return $Call.ByID(1868287224, threadID);
}

/**
 * CompactThread forces an immediate compression of older messages in the thread.
 */
export function CompactThread(threadID: string): $CancellablePromise<dtos$0.CompactThreadResponse | null> {
    return $Call.ByID(4038821936, threadID);
}

/**
 * CreateSubThread creates a specialized sub-chat thread for a project, volume, or chapter.
 */
export function CreateSubThread(req: dtos$0.CreateSubThreadRequest): $CancellablePromise<dtos$0.NovelClawThreadDTO | null> {
    return $Call.ByID(3092672811, req);
}

/**
 * DeleteThread deletes a sub-chat thread and its messages.
 */
export function DeleteThread(threadID: string): $CancellablePromise<void> {
    return $Call.ByID(2706514124, threadID);
}

/**
 * GetAutoCompactThreshold returns current threshold.
 */
export function GetAutoCompactThreshold(): $CancellablePromise<number> {
    return $Call.ByID(1054211722);
}

/**
 * GetOrCreateMainThread ensures a main thread exists for the project and returns it.
 */
export function GetOrCreateMainThread(projectID: string): $CancellablePromise<dtos$0.NovelClawThreadDTO | null> {
    return $Call.ByID(2408051293, projectID);
}

/**
 * ListMessages returns non-archived messages in chronological order for a thread.
 */
export function ListMessages(threadID: string): $CancellablePromise<dtos$0.NovelClawMessageDTO[] | null> {
    return $Call.ByID(3487399655, threadID);
}

/**
 * ListThreads returns all chat threads for a project with token counts.
 */
export function ListThreads(projectID: string): $CancellablePromise<dtos$0.NovelClawThreadDTO[] | null> {
    return $Call.ByID(3694401732, projectID);
}

/**
 * SendMessage sends a user message to NovelClaw and executes tools / returns reply.
 */
export function SendMessage(req: dtos$0.SendNovelClawMessageRequest): $CancellablePromise<dtos$0.NovelClawMessageDTO | null> {
    return $Call.ByID(3404420424, req);
}

/**
 * SetAutoCompactThreshold updates the threshold for auto-compacting context.
 */
export function SetAutoCompactThreshold(tokens: number): $CancellablePromise<void> {
    return $Call.ByID(694633166, tokens);
}

/**
 * UpdateThreadTitle changes the title of a sub-chat thread.
 */
export function UpdateThreadTitle(threadID: string, title: string): $CancellablePromise<void> {
    return $Call.ByID(3296355540, threadID, title);
}
