// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProjectService exposes project and chapter operations to the Wails v3 frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dtos$0 from "../dtos/models.js";

/**
 * AppendBookToProject parses an additional book/volume and appends its chapters to an existing project/series.
 */
export function AppendBookToProject(req: dtos$0.AppendBookRequest): $CancellablePromise<dtos$0.ProjectDTO | null> {
    return $Call.ByID(1516246532, req);
}

/**
 * CreateProject creates a new translation project from a DTO request.
 */
export function CreateProject(req: dtos$0.CreateProjectRequest): $CancellablePromise<void> {
    return $Call.ByID(2523494676, req);
}

/**
 * DeleteProject deletes a project and cascades related data.
 */
export function DeleteProject(id: string): $CancellablePromise<void> {
    return $Call.ByID(3894423153, id);
}

/**
 * GetChapter retrieves a specific chapter by its unique ID.
 */
export function GetChapter(chapterID: string): $CancellablePromise<dtos$0.ChapterDTO | null> {
    return $Call.ByID(3324435982, chapterID);
}

/**
 * GetProject retrieves project details by ID as a DTO.
 */
export function GetProject(id: string): $CancellablePromise<dtos$0.ProjectDTO | null> {
    return $Call.ByID(3059341362, id);
}

/**
 * ImportBook parses a novel file (EPUB, TXT, FB2) and ingests it into a new project.
 */
export function ImportBook(req: dtos$0.ImportBookRequest): $CancellablePromise<dtos$0.ProjectDTO | null> {
    return $Call.ByID(1316299139, req);
}

/**
 * ImportBooksBatch imports multiple files, either as separate projects or aggregated as a multi-volume series.
 */
export function ImportBooksBatch(req: dtos$0.BatchImportBookRequest): $CancellablePromise<dtos$0.BatchImportResultDTO | null> {
    return $Call.ByID(2839681992, req);
}

/**
 * InheritKnowledge copies character graph (L2) and glossary (L3) from a source project to a target project.
 */
export function InheritKnowledge(req: dtos$0.InheritKnowledgeRequest): $CancellablePromise<dtos$0.InheritKnowledgeResultDTO | null> {
    return $Call.ByID(4060499290, req);
}

/**
 * ListChapters retrieves all chapters belonging to a project ordered by chapter index.
 */
export function ListChapters(projectID: string): $CancellablePromise<dtos$0.ChapterDTO[] | null> {
    return $Call.ByID(3433591241, projectID);
}

/**
 * ListProjects lists all available projects as DTOs.
 */
export function ListProjects(): $CancellablePromise<dtos$0.ProjectDTO[] | null> {
    return $Call.ByID(4267051653);
}

/**
 * RenameProject updates the title of a project and returns the updated ProjectDTO.
 */
export function RenameProject(req: dtos$0.RenameProjectRequest): $CancellablePromise<dtos$0.ProjectDTO | null> {
    return $Call.ByID(2622689998, req);
}

/**
 * RollbackChapter restores the chapter translation and status to the latest saved checkpoint.
 */
export function RollbackChapter(projectID: string, chapterIndex: number): $CancellablePromise<dtos$0.ChapterDTO | null> {
    return $Call.ByID(641109836, projectID, chapterIndex);
}

/**
 * UpdateChapterTranslation applies direct user edits to a chapter's translated content.
 */
export function UpdateChapterTranslation(req: dtos$0.UpdateChapterInlineRequest): $CancellablePromise<void> {
    return $Call.ByID(3134624358, req);
}

/**
 * UpdateProjectLanguages updates translation language direction for a project and returns the updated ProjectDTO.
 */
export function UpdateProjectLanguages(req: dtos$0.UpdateProjectLanguagesRequest): $CancellablePromise<dtos$0.ProjectDTO | null> {
    return $Call.ByID(323078598, req);
}

/**
 * UpdateProjectStyle updates the style name and style guide prompt for a project and returns the updated ProjectDTO.
 */
export function UpdateProjectStyle(req: dtos$0.UpdateProjectStyleRequest): $CancellablePromise<dtos$0.ProjectDTO | null> {
    return $Call.ByID(1264848368, req);
}
