// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SkillService exposes modular skill management, presets, and token footprint analytics to Wails v3.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dtos$0 from "../dtos/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as skills$0 from "../../pkg/skills/models.js";

/**
 * ApplyCapabilityPreset sets the skills according to a 1-click bundle (Eco, Standard, Publishing).
 */
export function ApplyCapabilityPreset(projectID: string, presetName: string): $CancellablePromise<void> {
    return $Call.ByID(4168116436, projectID, presetName);
}

/**
 * GetActiveSkillsTokenWeight calculates the sum of estimated tokens for all active skills of a project.
 */
export function GetActiveSkillsTokenWeight(projectID: string): $CancellablePromise<number> {
    return $Call.ByID(2830257598, projectID);
}

/**
 * GetSkillPresets returns all available capability presets.
 */
export function GetSkillPresets(): $CancellablePromise<dtos$0.SkillPresetDTO[] | null> {
    return $Call.ByID(601880558);
}

/**
 * ListSkills returns all available modular skills and their current state for a project.
 */
export function ListSkills(projectID: string): $CancellablePromise<dtos$0.SkillDTO[] | null> {
    return $Call.ByID(1552142845, projectID);
}

/**
 * Registry returns the underlying Skill Registry.
 */
export function Registry(): $CancellablePromise<skills$0.Registry | null> {
    return $Call.ByID(195384488);
}

/**
 * ResetSkillToDefault restores a skill's rules and state to its built-in values.
 */
export function ResetSkillToDefault(projectID: string, skillID: string): $CancellablePromise<void> {
    return $Call.ByID(3048713311, projectID, skillID);
}

/**
 * ToggleSkill switches a specific skill on or off for a project.
 */
export function ToggleSkill(projectID: string, skillID: string, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3910511792, projectID, skillID, enabled);
}

/**
 * UpdateSkillCustomRules saves user-defined prompt rules for a skill.
 */
export function UpdateSkillCustomRules(projectID: string, skillID: string, customRules: string): $CancellablePromise<void> {
    return $Call.ByID(1631319035, projectID, skillID, customRules);
}
