// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SoulService provides coworker personality interactions, soul profile CRUD, and hot-steering controls to Wails v3.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dtos$0 from "../dtos/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as soul$0 from "../../pkg/soul/models.js";

/**
 * Controller exposes the underlying soul controller for engine-level coordination.
 */
export function Controller(): $CancellablePromise<soul$0.Controller | null> {
    return $Call.ByID(3393150599).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteCustomSoul deletes a custom soul profile from disk and memory.
 */
export function DeleteCustomSoul(soulID: string): $CancellablePromise<void> {
    return $Call.ByID(4241468412, soulID);
}

/**
 * ExportSoulMarkdown exports a soul profile formatted as *.soul.md text.
 */
export function ExportSoulMarkdown(soulID: string): $CancellablePromise<string> {
    return $Call.ByID(4102742471, soulID);
}

/**
 * GetActiveSoul returns the active soul for a project or the global active soul.
 */
export function GetActiveSoul(projectID: string): $CancellablePromise<dtos$0.SoulDTO> {
    return $Call.ByID(411264592, projectID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetSoul returns the active Soul companion metadata and current mood.
 */
export function GetSoul(): $CancellablePromise<dtos$0.SoulDTO> {
    return $Call.ByID(3056050782).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ImportSoulMarkdown imports and validates a soul profile from *.soul.md text.
 */
export function ImportSoulMarkdown(content: string): $CancellablePromise<dtos$0.SoulDTO> {
    return $Call.ByID(892853460, content).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ListAvailableSouls returns all registered soul profiles.
 */
export function ListAvailableSouls(): $CancellablePromise<dtos$0.SoulDTO[]> {
    return $Call.ByID(3770236386).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * RestoreDefaultSouls resets built-in default souls to their factory values.
 */
export function RestoreDefaultSouls(): $CancellablePromise<void> {
    return $Call.ByID(2938360260);
}

/**
 * SaveCustomSoul persists a custom soul profile to disk and memory.
 */
export function SaveCustomSoul(soulDTO: dtos$0.SoulDTO): $CancellablePromise<void> {
    return $Call.ByID(498948726, soulDTO);
}

/**
 * SetActiveSoul changes the active soul for a project and emits a soul:changed event to frontend.
 */
export function SetActiveSoul(projectID: string, soulID: string): $CancellablePromise<void> {
    return $Call.ByID(2733100484, projectID, soulID);
}

/**
 * TriggerSteerAction directly issues emergency stops or hot style patches without chatting.
 */
export function TriggerSteerAction(req: dtos$0.SteerActionRequest): $CancellablePromise<dtos$0.SteerActionResultDTO> {
    return $Call.ByID(2182356876, req).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = soul$0.Controller.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = dtos$0.SoulDTO.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = dtos$0.SteerActionResultDTO.createFrom;
