// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TranslationService exposes multi-mode chapter translation and benchmark execution to Wails v3 frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dtos$0 from "../dtos/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as auditor$0 from "../../pkg/auditor/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as skills$0 from "../../pkg/skills/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as voice$0 from "../../pkg/voice/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as worldbible$0 from "../../pkg/worldbible/models.js";

/**
 * AutoScoutStyle analyzes opening narrative chapters of a novel and generates a tailored style guide.
 */
export function AutoScoutStyle(req: dtos$0.AutoScoutStyleRequest): $CancellablePromise<dtos$0.AutoScoutStyleResponse | null> {
    return $Call.ByID(2283356949, req);
}

/**
 * CancelTranslation requests an immediate emergency abort of an in-flight translation job.
 */
export function CancelTranslation(jobID: string): $CancellablePromise<boolean> {
    return $Call.ByID(3147152322, jobID);
}

/**
 * PreviewStyle translates a raw excerpt with the specified style instructions using the configured LLM.
 */
export function PreviewStyle(req: dtos$0.PreviewStyleRequest): $CancellablePromise<dtos$0.PreviewStyleResponse | null> {
    return $Call.ByID(2710099200, req);
}

/**
 * ResolveAskHuman sends the human decision back to the waiting translation worker.
 */
export function ResolveAskHuman(jobID: string, answer: string): $CancellablePromise<boolean> {
    return $Call.ByID(4116150061, jobID, answer);
}

/**
 * RunBenchmark executes a comparative benchmark across selected modes and returns a report.
 */
export function RunBenchmark(req: dtos$0.StartBenchmarkRequest): $CancellablePromise<dtos$0.BenchmarkReportDTO | null> {
    return $Call.ByID(3030309481, req);
}

/**
 * SetPlotAuditor connects the plot consistency auditor.
 */
export function SetPlotAuditor(a: auditor$0.PlotAuditor | null): $CancellablePromise<void> {
    return $Call.ByID(4126047362, a);
}

/**
 * SetSkillRegistry connects the modular skills registry.
 */
export function SetSkillRegistry(reg: skills$0.Registry | null): $CancellablePromise<void> {
    return $Call.ByID(2408802975, reg);
}

/**
 * SetVoiceRegistry connects the character voice persona registry.
 */
export function SetVoiceRegistry(r: voice$0.Registry | null): $CancellablePromise<void> {
    return $Call.ByID(2119960808, r);
}

/**
 * SetWorldBibleMatcher connects the Aho-Corasick World Bible matcher.
 */
export function SetWorldBibleMatcher(m: worldbible$0.Matcher | null): $CancellablePromise<void> {
    return $Call.ByID(134731725, m);
}

/**
 * SoftStopTranslation requests an active translation job to stop safely after the current segment.
 */
export function SoftStopTranslation(jobID: string): $CancellablePromise<boolean> {
    return $Call.ByID(395283972, jobID);
}

/**
 * TranslateChapter coordinates chapter translation using the selected mode and options.
 */
export function TranslateChapter(req: dtos$0.StartTranslationRequest): $CancellablePromise<dtos$0.ExecutionTelemetryDTO | null> {
    return $Call.ByID(2209991034, req);
}
