// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WorldBibleService coordinates the Universal World Bible, Autonomous World Builder,
 * Reflexion Diff-Learning Distiller, and Character Voice/Plot Auditor for Wails v3.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dtos$0 from "../dtos/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as skills$0 from "../../pkg/skills/models.js";

/**
 * DeleteCategory deletes a category and cascades to its entries.
 */
export function DeleteCategory(id: string): $CancellablePromise<void> {
    return $Call.ByID(55253185, id);
}

/**
 * DeleteEntry removes an entry from the World Bible.
 */
export function DeleteEntry(id: string): $CancellablePromise<void> {
    return $Call.ByID(4190956803, id);
}

/**
 * ExportWorldBibleJSON generates a structured JSON export.
 */
export function ExportWorldBibleJSON(projectID: string): $CancellablePromise<string> {
    return $Call.ByID(11781888, projectID);
}

/**
 * ExportWorldBibleMarkdown generates a complete WORLD_BIBLE.md export.
 */
export function ExportWorldBibleMarkdown(projectID: string): $CancellablePromise<string> {
    return $Call.ByID(798988323, projectID);
}

/**
 * ImportWorldBibleJSON imports categories and entries from JSON into a project.
 */
export function ImportWorldBibleJSON(projectID: string, jsonStr: string): $CancellablePromise<[number, number]> {
    return $Call.ByID(957034235, projectID, jsonStr);
}

/**
 * LearnFromEdits analyzes edits made to a chapter and persists evolved rules via the Distiller.
 */
export function LearnFromEdits(projectID: string, chapterIndex: number, notes: string): $CancellablePromise<dtos$0.LearnResultDTO | null> {
    return $Call.ByID(3155196729, projectID, chapterIndex, notes);
}

/**
 * ListCategories returns all categories defined for a project.
 */
export function ListCategories(projectID: string): $CancellablePromise<dtos$0.WorldCategoryDTO[] | null> {
    return $Call.ByID(1758920838, projectID);
}

/**
 * ListCharacterVoices returns registered voice profiles for a project.
 */
export function ListCharacterVoices(projectID: string): $CancellablePromise<dtos$0.CharacterVoiceDTO[] | null> {
    return $Call.ByID(3948420418, projectID);
}

/**
 * ListEntries returns world entries for a project, optionally filtered by category.
 */
export function ListEntries(projectID: string, categoryID: string): $CancellablePromise<dtos$0.WorldEntryDTO[] | null> {
    return $Call.ByID(2233430182, projectID, categoryID);
}

/**
 * ResetSkillsToDefault provides a 1-click factory reset wiping evolved skill mutations for a project.
 */
export function ResetSkillsToDefault(projectID: string): $CancellablePromise<void> {
    return $Call.ByID(2451177791, projectID);
}

/**
 * ScanAndBuildWorld triggers the autonomous builder agent to scan novel chapters and synthesize the World Bible.
 */
export function ScanAndBuildWorld(projectID: string, startChap: number, endChap: number): $CancellablePromise<dtos$0.ScanWorldResponse | null> {
    return $Call.ByID(1011788844, projectID, startChap, endChap);
}

/**
 * SetSkillStorage overrides skillStorage (primarily for testing with isolated temporary dirs).
 */
export function SetSkillStorage(sm: skills$0.StorageManager | null): $CancellablePromise<void> {
    return $Call.ByID(4224362216, sm);
}

/**
 * SyncVoicesFromGraph populates voice profiles from knowledge graph character entities.
 */
export function SyncVoicesFromGraph(projectID: string): $CancellablePromise<number> {
    return $Call.ByID(362221054, projectID);
}

/**
 * UpsertCategory adds or modifies a dynamic world taxonomy category.
 */
export function UpsertCategory(req: dtos$0.UpsertWorldCategoryRequest): $CancellablePromise<dtos$0.WorldCategoryDTO | null> {
    return $Call.ByID(3517639673, req);
}

/**
 * UpsertCharacterVoice registers or updates a character voice profile.
 */
export function UpsertCharacterVoice(req: dtos$0.UpsertVoiceRequest): $CancellablePromise<void> {
    return $Call.ByID(469342978, req);
}

/**
 * UpsertEntry adds or modifies a Lorebook entry.
 */
export function UpsertEntry(req: dtos$0.UpsertWorldEntryRequest): $CancellablePromise<dtos$0.WorldEntryDTO | null> {
    return $Call.ByID(3981748491, req);
}

/**
 * VerifyEntry sets the verified status (1 = approved by human, 0 = AI suggested).
 */
export function VerifyEntry(id: string, verified: boolean): $CancellablePromise<void> {
    return $Call.ByID(1631357437, id, verified);
}
