// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Matcher manages Trie-based keyword matching on World Bible entries to inject into LLM prompts.
 */
export interface Matcher {
}
