// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Matcher manages Trie-based keyword matching on World Bible entries to inject into LLM prompts.
 */
export class Matcher {

    /** Creates a new Matcher instance. */
    constructor($$source: Partial<Matcher> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Matcher instance from a string or object.
     */
    static createFrom($$source: any = {}): Matcher {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Matcher($$parsedSource as Partial<Matcher>);
    }
}
