package r19

import (
	"bufio"
	"io"
	"os"
	"strings"
)

// DefaultTerms provides built-in multi-lingual sensitive term mappings across CN, JP, KR, EN, and VI.
var DefaultTerms = map[string]string{
	// ==========================================
	// 1. CHINESE (CN) - Sắc hiệp, Tu tiên, Đam mỹ, Ngôn tình 18+
	// ==========================================
	// --- Giải phẫu nhạy cảm (Anatomy) ---
	"处女膜":   "màng trinh",
	"小穴":    "tiểu huyệt",
	"花穴":    "hoa huyệt",
	"蜜穴":    "mật huyệt",
	"粉穴":    "phấn huyệt",
	"肉缝":    "khe thịt",
	"花径":    "lối hoa",
	"玉门":    "ngọc môn",
	"私处":    "chỗ kín",
	"下体":    "hạ thể",
	"私密处":   "vùng kín",
	"阴道":    "âm đạo",
	"阴蒂":    "âm vật",
	"阴唇":    "âm môi",
	"后穴":    "hậu huyệt",
	"后庭":    "hậu đình",
	"菊穴":    "cúc huyệt",
	"菊花":    "cúc hoa",
	"肉棒":    "côn thịt",
	"阳具":    "dương cụ",
	"肉刃":    "nhục nhẫn",
	"玉柱":    "ngọc trụ",
	"龟头":    "quy đầu",
	"阴茎":    "dương vật",
	"睾丸":    "tinh hoàn",
	"囊袋":    "túi tinh",
	"乳头":    "đầu ti",
	"乳晕":    "quầng vú",
	"乳房":    "bầu ngực",
	"酥胸":    "khuôn ngực mềm mại",
	"雪峰":    "đôi gò bồng đảo",
	"双峰":    "đôi gò bồng đào",
	"巨乳":    "ngực khủng",
	"贫乳":    "ngực lép",
	"丰臀":    "bờ mông đẫy đà",
	"翘臀":    "bờ mông cong vút",
	"胴体":    "thân thể mềm mại",
	"玉体":    "ngọc thể",
	"娇躯":    "kiều khu",
	"阴毛":    "lông mu",

	// --- Hành vi tình dục & Khoái cảm (Acts & Climax) ---
	"做爱":      "làm tình",
	"性交":      "giao cấu",
	"交尾":      "giao phối",
	"交合":      "giao hợp",
	"合体":      "hợp thể",
	"云雨":      "mây mưa",
	"欢好":      "hoan hảo",
	"承欢":      "thừa hoan",
	"索欢":      "đòi hỏi hoan ái",
	"欢愉":      "khoái lạc",
	"欢爱":      "hoan ái",
	"翻云覆雨":    "mây mưa hoan lạc",
	"巫山云雨":    "mây mưa ân ái",
	"侍寝":      "hầu ngủ",
	"抽送":      "nhấp nhổm ra vào",
	"挺进":      "tiến sâu vào",
	"挺入":      "đâm sâu vào",
	"冲撞":      "va chạm kịch liệt",
	"耸动":      "chuyển động hông",
	"贯穿":      "xuyên qua",
	"侵入":      "xâm nhập",
	"破处":      "phá trinh",
	"开苞":      "khai hoa",
	"中出":      "xuất tinh trong",
	"内射":      "xuất vào trong",
	"中出到怀孕":   "xuất tinh trong đến khi mang thai",
	"射精":      "xuất tinh",
	"高潮":      "lên đỉnh",
	"绝顶":      "lên đỉnh cực khoái",
	"潮吹":      "triều xuy",
	"泄身":      "xuất tinh",
	"泄精":      "phóng tinh",
	"自慰":      "tự sướng",
	"手淫":      "thủ dâm",
	"前戏":      "màn dạo đầu",
	"后入":      "tư thế từ phía sau",
	"深喉":      "ngậm sâu vào họng",
	"口交":      "quan hệ bằng miệng",
	"乳交":      "kẹp giữa ngực",
	"足交":      "dùng chân kích thích",
	"呻吟":      "rên rỉ",
	"娇喘":      "thở gấp kiều diễm",
	"浪叫":      "tiếng rên gợi tình",
	"浪语":      "lời nói khêu gợi",

	// --- Dịch cơ thể (Fluids) ---
	"爱液":    "ái dịch",
	"蜜液":    "mật dịch",
	"蜜汁":    "mật dịch ngọt ngào",
	"淫液":    "dâm dịch",
	"淫水":    "dâm thủy",
	"淫汁":    "dâm dịch",
	"白浊":    "chất lỏng màu trắng đục",
	"精液":    "tinh dịch",
	"阳精":    "dương tinh",
	"元阳":    "nguyên dương",
	"元阴":    "nguyên âm",
	"处女血":   "máu trinh",

	// --- Cấm kỵ, Bạo lực & Đồ chơi (Taboo, BDSM & Paraphilia) ---
	"強姦":    "cưỡng bức",
	"强奸":    "cưỡng bức",
	"强暴":    "cưỡng bức",
	"輪姦":    "luân hiếp",
	"轮奸":    "luân hiếp",
	"迷奸":    "chuốc thuốc cưỡng bức",
	"诱奸":    "dụ dỗ cưỡng bức",
	"凌辱":    "lăng nhục",
	"陵辱":    "lăng nhục",
	"调教":    "điều giáo",
	"拘束":    "trói buộc",
	"捆绑":    "trói buộc cơ thể",
	"绳缚":    "trói dây nghệ thuật",
	"禁锢":    "giam cầm",
	"乱伦":    "loạn luân",
	"媚药":    "mị dược",
	"春药":    "xuân dược",
	"催情":    "kích dục",
	"淫乱":    "dâm loạn",
	"淫荡":    "dâm đãng",
	"骚货":    "kẻ dâm đãng",
	"贱人":    "tiện nhân",
	"母狗":    "nô lệ tình dục",
	"性奴":    "nô lệ tình dục",
	"禁脔":    "đồ chơi độc chiếm",
	"玩物":    "đồ chơi tình dục",
	"鼎炉":    "đỉnh lô",
	"炉鼎":    "lô đỉnh",
	"采补":    "thải bổ",
	"肛塞":    "nút hậu môn",
	"跳蛋":    "trứng rung",
	"假阳具":   "dương vật giả",
	"皮鞭":    "roi da",
	"口塞":    "bóng ngậm miệng",
	"赤裸":    "trần trụi",
	"赤身裸体":  "trần truồng",
	"一丝不挂":  "không một mảnh vải che thân",
	"剥光":    "lột sạch",
	"褪去衣衫":  "cởi bỏ xiêm y",

	// ==========================================
	// 2. JAPANESE (JP) - Light Novel, Web Novel, Eroge, Hentai
	// ==========================================
	// --- Giải phẫu (Anatomy) ---
	"おまんこ":   "vùng kín",
	"まんこ":    "vùng kín",
	"マンコ":    "vùng kín",
	"膣":      "âm đạo",
	"膣内":     "bên trong âm đạo",
	"膣奥":     "sâu trong âm đạo",
	"膣壁":     "thành âm đạo",
	"肉壺":     "khe thịt",
	"肉壁":     "vách thịt",
	"蜜壺":     "mật huyệt",
	"蜜口":     "miệng huyệt",
	"子宮":     "tử cung",
	"子宮口":    "cổ tử cung",
	"秘部":     "chỗ kín",
	"秘所":     "chỗ thầm kín",
	"秘肉":     "phần thịt nhạy cảm",
	"陰核":     "âm vật",
	"クリトリス":  "âm vật",
	"クリ":     "âm vật",
	"陰唇":     "môi âm hộ",
	"処女膜":    "màng trinh",
	"おちんちん":  "cậu bé",
	"チンポ":    "dương vật",
	"ちんこ":    "cậu nhỏ",
	"陰茎":     "dương vật",
	"ペニス":    "dương vật",
	"亀頭":     "quy đầu",
	"雁首":     "đầu khấc quy đầu",
	"怒張":     "cương cứng",
	"剛直":     "cương cứng cực đại",
	"金玉":     "tinh hoàn",
	"玉袋":     "bìu dái",
	"アナル":    "hậu môn",
	"菊門":     "hậu môn",
	"門門":     "cửa hậu",
	"乳首":     "đầu ti",
	"乳輪":     "quầng ngực",
	"爆乳":     "ngực khủng",
	"貧乳":     "ngực phẳng",
	"微乳":     "ngực nhỏ",
	"陥没乳首":   "đầu ti thụt",
	"突起":     "đầu ti nhô cao",
	"恥丘":     "gò mu",

	// --- Hành vi & Cảm giác (Acts & Sensations) ---
	"セックス":   "làm tình",
	"中出し":    "xuất tinh trong",
	"膣内射精":   "xuất tinh vào âm đạo",
	"外出し":    "xuất tinh ra ngoài",
	"ぶっかけ":   "bắn tinh lên người",
	"顔射":     "bắn tinh lên mặt",
	"放尿":     "tiểu tiện",
	"潮吹き":    "triều xuy",
	"絶頂":     "lên đỉnh",
	"アクメ":    "lên đỉnh cực khoái",
	"昇天":     "thăng hoa cực lạc",
	"悶絶":     "ngây ngất khôn cùng",
	"痙攣":     "co giật liên hồi",
	"ビクビク":   "giật nảy từng cơn",
	"ピクピク":   "co giật nhè nhẹ",
	"イキ狂い":   "lên đỉnh điên cuồng",
	"イカせる":   "khiến đối phương lên đỉnh",
	"達する":    "chạm tới cực khoái",
	"オナニー":   "tự sướng",
	"手コキ":    "dùng tay vuốt ve kích thích",
	"パイズリ":   "kẹp dương vật giữa ngực",
	"フェラチオ":  "kích thích bằng miệng",
	"フェラ":    "thổi kèn",
	"クンニ":    "liếm vùng kín",
	"クンニリングス": "liếm láp âm vật",
	"素股":     "cọ xát giữa hai đùi",
	"騎乗位":    "tư thế cưỡi ngựa",
	"正常位":    "tư thế truyền thống",
	"バック":    "tư thế từ phía sau",
	"後背位":    "tư thế từ phía sau",
	"対面座位":   "ngồi đối diện ôm nhau",
	"生ハメ":    "quan hệ trực tiếp không bảo vệ",
	"結合":     "kết nối thân thể",
	"挿入":     "đưa vào bên trong",
	"貫く":     "đâm xuyên",
	"抉る":     "ngoáy sâu vào",
	"喘ぎ":     "tiếng thở gấp",
	"喘ぎ声":    "tiếng rên rỉ",
	"嬌声":     "tiếng kêu nũng nịu khêu gợi",
	"アヘ顔":    "khuôn mặt khoái lạc đờ đẫn",
	"あへ顔":    "khuôn mặt đờ đẫn sung sướng",
	"キツキツ":   "bó chặt chít khít",
	"ガバガバ":   "nới lỏng rộng",
	"ぬちゃぬちゃ": "âm thanh ẩm ướt nhớp nháp",
	"ぐちゅぐちゅ": "âm thanh ướt át kẹp chặt",
	"じゅぽじゅぽ": "âm thanh mút mát ướt át",

	// --- Dịch tiết (Secretions) ---
	"ザーメン":   "tinh dịch",
	"白濁液":    "dòng chất lỏng màu trắng đục",
	"愛液":     "ái dịch",
	"蜜":      "mật dịch",
	"潮":      "dòng nước triều xuy",
	"我慢汁":    "chất dịch kích thích hưng phấn",

	// --- Trạng thái & BDSM (States & Fetish) ---
	"処女":     "trinh nữ",
	"破瓜":     "phá trinh",
	"発情":     "phát tình",
	"媚薬":     "mị dược",
	"催眠":     "thôi miên",
	"洗脳":     "tẩy não",
	"痴漢":     "biến thái quấy rối",
	"痴女":     "dâm nữ",
	"露出":     "phơi bày thân thể",
	"露出狂":    "kẻ thích phơi bày",
	"変態":     "biến thái",
	"淫靡":     "dâm mĩ mê hoặc",
	"緊縛":     "trói buộc bằng dây",
	"調教":     "điều giáo",
	"奴隷":     "nô lệ",
	"肉便器":    "công cụ giải tỏa tình dục",
	"バイブ":    "máy rung",
	"ローター":   "trứng rung",
	"ディルド":   "dương vật giả",
	"電マ":     "máy mát-xa rung",

	// ==========================================
	// 3. KOREAN (KR) - Webnovel, Manhwa 19+, R19
	// ==========================================
	// --- Giải phẫu (Anatomy) ---
	"자지":     "cậu nhỏ",
	"보지":     "vùng kín",
	"씹":      "chỗ kín",
	"좆":      "của quý",
	"음경":     "dương vật",
	"페니스":    "dương vật",
	"성기":     "bộ phận sinh dục",
	"질":      "âm đạo",
	"질벽":     "thành âm đạo",
	"자궁":     "tử cung",
	"자궁구":    "cổ tử cung",
	"클리토리스":  "âm vật",
	"음핵":     "âm vật",
	"소음순":    "môi bé",
	"대음순":    "môi lớn",
	"처녀막":    "màng trinh",
	"항문":     "hậu môn",
	"애널":     "cửa hậu",
	"가슴":     "bầu ngực",
	"유두":     "đầu ti",
	"젖꼭지":    "đầu ngực",
	"거유":     "ngực to",
	"빈유":     "ngực nhỏ",
	"엉덩이":    "bờ mông",
	"음모":     "lông mu",

	// --- Hành vi & Khái niệm (Acts & Concepts) ---
	"섹스":     "làm tình",
	"성교":     "giao cấu",
	"관계":     "quan hệ thân xác",
	"교미":     "giao phối",
	"떡치다":    "mây mưa ân ái",
	"박다":     "thọc sâu vào",
	"쑤시다":    "đâm rút bên trong",
	"사정":     "xuất tinh",
	"질내사정":   "xuất tinh trong",
	"안에 싸다":  "xuất thẳng vào bên trong",
	"노콘":     "không dùng bao cao su",
	"임신":     "mang thai",
	"오르가즘":   "cực khoái",
	"절정":     "lên đỉnh",
	"분수":     "triều xuy phun nước",
	"자위":     "thủ dâm",
	"딸딸이":    "thủ dâm",
	"펠라치오":   "kích thích bằng miệng",
	"펠라":     "thổi kèn",
	"커닐링구스":  "liếm vùng kín",
	"파이즈리":   "kẹp giữa ngực",
	"기승위":    "tư thế ngồi lên trên",
	"후배위":    "tư thế từ phía sau",
	"정상위":    "tư thế truyền thống",
	"신음":     "tiếng rên rỉ",
	"교성":     "tiếng rên khêu gợi",
	"헐떡임":    "tiếng thở dốc",
	"아헤가오":   "gương mặt khoái lạc",
	"야설":     "tiểu thuyết sắc tình 18+",

	// --- Dịch & Trạng thái (Fluids & States) ---
	"애액":    "ái dịch",
	"음액":    "dâm dịch",
	"정액":    "tinh dịch",
	"쿠퍼액":   "dịch hưng phấn",
	"쿠퍼스":   "dịch bôi trơn",
	"최음제":   "thuốc kích dục",
	"발정":    "phát tình",
	"최면":    "thôi miên",
	"조교":    "điều giáo huấn luyện",
	"능욕":    "lăng nhục",
	"강간":    "cưỡng bức",
	"윤간":    "luân hiếp",
	"감금":    "giam cầm ép buộc",
	"결박":    "trói chặt",
	"노예":    "nô lệ",
	"육변기":   "công cụ tình dục",
	"음란":    "dâm loạn",
	"흥분":    "hưng phấn cao độ",

	// ==========================================
	// 4. ENGLISH (EN) - Erotica, Mature Fiction, RoyalRoad NSFW
	// ==========================================
	// --- Anatomy ---
	"penis":         "dương vật",
	"cock":          "cậu nhỏ",
	"dick":          "của quý",
	"shaft":         "thân dương vật",
	"glans":         "quy đầu",
	"testicles":     "tinh hoàn",
	"scrotum":       "bìu dái",
	"balls":         "hai hòn tinh hoàn",
	"vagina":        "âm đạo",
	"pussy":         "vùng kín",
	"cunt":          "hoa huyệt",
	"slit":          "khe thịt",
	"labia":         "môi âm hộ",
	"clitoris":      "âm vật",
	"clit":          "hạt le âm vật",
	"cervix":        "cổ tử cung",
	"womb":          "tử cung",
	"breasts":       "bầu ngực",
	"boobs":         "đôi gò bồng đảo",
	"tits":          "cặp nhũ hoa",
	"nipple":        "đầu ti",
	"nipples":       "đầu ngực",
	"areola":        "quầng vú",
	"anus":          "hậu môn",
	"asshole":       "lỗ hậu môn",
	"buttocks":      "bờ mông",
	"perineum":      "đáy chậu",

	// --- Actions & Sensations ---
	"intercourse":   "giao hợp",
	"penetration":   "sự thâm nhập",
	"penetrate":     "thâm nhập sâu",
	"thrusting":     "đẩy hông nhịp nhàng",
	"pounding":      "dộng mạnh mẽ",
	"creampie":      "xuất tinh bên trong",
	"cumshot":       "bắn tinh",
	"ejaculation":   "sự xuất tinh",
	"ejaculate":     "xuất tinh",
	"orgasm":        "cực khoái",
	"climax":        "lên đỉnh",
	"squirting":     "triều xuy phun nước",
	"squirt":        "phun trào ái dịch",
	"masturbation":  "thủ dâm",
	"masturbate":    "thủ dâm",
	"fingering":     "dùng ngón tay kích thích",
	"blowjob":       "thổi kèn",
	"fellatio":      "kích thích bằng miệng",
	"deepthroat":    "ngậm sâu vào cuống họng",
	"cunnilingus":   "liếm láp vùng kín",
	"handjob":       "dùng tay kích thích",
	"titfuck":       "kẹp dương vật giữa hai ngực",
	"rimjob":        "liếm hậu môn",
	"missionary":    "tư thế truyền thống",
	"doggystyle":    "tư thế từ phía sau",
	"cowgirl":       "tư thế cưỡi ngựa",
	"groaning":      "tiếng rên trầm đục",
	"moaning":       "tiếng rên rỉ ngọt ngào",
	"gasping":       "hơi thở dồn dập",

	// --- Fluids & States ---
	"cum":           "tinh dịch",
	"semen":         "tinh dịch",
	"sperm":         "tinh trùng",
	"precum":        "dịch bôi trơn hưng phấn",
	"arousal":       "sự kích thích ham muốn",
	"aroused":       "hưng phấn",
	"horny":         "khao khát dục vọng",
	"wetness":       "sự ướt át dâm dịch",
	"lubricated":    "được bôi trơn trơn tru",
	"dripping":      "nhỏ giọt ướt đẫm",
	"aphrodisiac":   "thuốc kích dục",
	"estrus":        "kỳ phát tình",
	"heat":          "phát dục nồng nặc",

	// --- BDSM & Taboo ---
	"bondage":       "trói buộc gợi cảm",
	"shibari":       "nghệ thuật trói dây",
	"handcuffed":    "bị còng tay",
	"spanking":      "đánh vào mông trừng phạt",
	"gagged":        "bị bịt miệng",
	"chastity":      "khóa trinh tiết",
	"dildo":         "dương vật giả",
	"vibrator":      "máy rung",
	"butt plug":     "nút chặn hậu môn",
	"gangbang":      "quan hệ tập thể",
	"gang-bang":     "quan hệ tập thể",
	"rape":          "hành vi cưỡng bức",
	"non-consensual": "không có sự đồng thuận",
	"submissive":    "kẻ phục tùng",
	"dominant":      "người thống trị",

	// ==========================================
	// 5. VIETNAMESE (VI) - Thuật ngữ đối chiếu & Văn phong xuất bản
	// ==========================================
	"làm tình":     "làm tình",
	"giao cấu":     "giao cấu",
	"xuất tinh":    "xuất tinh",
	"phóng tinh":   "phóng tinh",
	"bắn tinh":     "bắn tinh",
	"cực khoái":    "cực khoái",
	"lên đỉnh":     "lên đỉnh",
	"thủ dâm":      "thủ dâm",
	"tự sướng":     "tự sướng",
	"khe thịt":     "khe thịt",
	"môi âm hộ":    "môi âm hộ",
	"âm hộ":        "âm hộ",
	"âm đạo":       "âm đạo",
	"màng trinh":   "màng trinh",
	"máu trinh":    "máu trinh",
	"phá trinh":    "phá trinh",
	"dương vật":    "dương vật",
	"quy đầu":      "quy đầu",
	"tinh hoàn":    "tinh hoàn",
	"tinh dịch":    "tinh dịch",
	"ái dịch":      "ái dịch",
	"dâm dịch":     "dâm dịch",
	"dâm thủy":     "dâm thủy",
	"nước nôi":     "nước nôi",
	"ướt đẫm":      "ướt đẫm",
	"rên rỉ":       "rên rỉ",
	"thở dốc":      "thở dốc",
	"cưỡng bức":    "cưỡng bức",
	"hiếp dâm":     "hiếp dâm",
	"luân hiếp":    "luân hiếp",
	"loạn luân":    "loạn luân",
	"thuốc kích dục": "thuốc kích dục",
	"mị dược":      "mị dược",
	"xuân dược":    "xuân dược",
	"phát tình":    "phát tình",
	"thôi miên":    "thôi miên",
	"trói buộc":    "trói buộc",
	"nô lệ tình dục": "nô lệ tình dục",
	"đỉnh lô":      "đỉnh lô",
	"thải bổ":      "thải bổ",
	"trần truồng":  "trần truồng",
	"trần trụi":    "trần trụi",
	"khỏa thân":    "khỏa thân",
	"khoái lạc":    "khoái lạc",
	"hoan lạc":     "hoan lạc",
	"dâm loạn":     "dâm loạn",
	"dâm đãng":     "dâm đãng",
}

// LoadTermsFromReader reads custom sensitive term mappings from an io.Reader (format: source = translation or source\ttranslation).
func LoadTermsFromReader(r io.Reader) (map[string]string, error) {
	terms := make(map[string]string)
	scanner := bufio.NewScanner(r)

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, "//") {
			continue
		}

		var src, dst string
		if strings.Contains(line, "=") {
			parts := strings.SplitN(line, "=", 2)
			src = strings.TrimSpace(parts[0])
			dst = strings.TrimSpace(parts[1])
		} else if strings.Contains(line, "\t") {
			parts := strings.SplitN(line, "\t", 2)
			src = strings.TrimSpace(parts[0])
			dst = strings.TrimSpace(parts[1])
		} else {
			src = line
			dst = line
		}

		if src != "" {
			terms[src] = dst
		}
	}

	return terms, scanner.Err()
}

// LoadTermsFromFile reads custom term mappings from a disk file.
func LoadTermsFromFile(path string) (map[string]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	return LoadTermsFromReader(f)
}
