// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Registry stores and matches character voices per project.
 */
export class Registry {

    /** Creates a new Registry instance. */
    constructor($$source: Partial<Registry> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Registry instance from a string or object.
     */
    static createFrom($$source: any = {}): Registry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Registry($$parsedSource as Partial<Registry>);
    }
}
