// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PlotAuditor inspects translated chapters against known entity states in the temporal graph.
 */
export interface PlotAuditor {
}
